// UI copy only. User-authored titles, slide content and Bible/song sources are never catalog keys.
import type { WorkspaceLanguage } from './workspaceLanguage'

export const russianWorkspaceText: Readonly<Record<string, string>> = {
  "Workspace view": "Вид рабочей области",
  "On screen": "На экране",
  "Slide was not shown: {error}": "Слайд не показан: {error}",
  "The slide could not be shown. The current screen is unchanged.": "Не удалось показать слайд. Текущий экран остался прежним.",
  "The live slide was removed from the draft. Choose another slide, or return to Load. The current screen is unchanged.": "Показанный слайд удалён из черновика. Выберите другой слайд или вернитесь к загрузке. Текущий экран остался прежним.",
  "That slide was removed from the draft. Choose another slide, or return to Load. The current screen is unchanged.": "Этот слайд удалён из черновика. Выберите другой слайд или вернитесь к загрузке. Текущий экран остался прежним.",
  "{title} is open at Community version {version}.": "Открыто: {title}. Версия Community: {version}.",
  "{title} is open from this computer.": "Открыто с этого компьютера: {title}.",
  "Click a slide to show it · Double-click to edit": "Нажмите слайд, чтобы показать · Двойной щелчок для редактирования",
  "Slides": "Слайды",
  "Edit": "Редактировать",
  "Edit slide": "Редактировать слайд",
  "Preview": "Предпросмотр",
  "Prepare sermon": "Подготовка проповеди",
  "Plan service": "План служения",
  "Saving paused because this document changed elsewhere. Your latest draft is safe here.": "Сохранение приостановлено: документ изменён в другом месте. Ваш последний черновик сохранён здесь.",
  "Draft kept locally · review conflict": "Черновик сохранён локально · сравните версии",
  "Community returned a saved version for an unexpected document.": "Community вернул сохранённую версию другого документа. Ваш черновик остаётся на этом компьютере.",
  "The saved version changed again. Review the updated preview before choosing.": "Сохранённая версия снова изменилась. Просмотрите новый вариант перед выбором.",
  "Another save arrived while yours was saving. Your draft is safe; review the latest version and choose again.": "Во время сохранения появилась другая версия. Ваш черновик сохранён здесь; просмотрите последнюю версию и выберите снова.",
  "Review saved version": "Сравнить с сохранённой версией",
  "The document changed while you were reviewing it. Open the review again.": "Во время сравнения документ изменился. Откройте сравнение снова.",
  "Your draft changed while this review was open. Review its updated preview before choosing.": "Во время сравнения ваш черновик изменился. Просмотрите обновлённый вариант перед выбором.",
  "Using the saved version. Previous saved versions remain in history.": "Открыта сохранённая версия. Все предыдущие сохранённые версии остались в истории.",
  "History is read-only until you resolve the save conflict. Your draft stays in the editor.": "До разрешения конфликта история доступна только для просмотра. Ваш черновик остаётся в редакторе.",
  "English": "Английский",
  "Russian": "Русский",
  "Stage-Facing Screen": "Экран для сцены",
  "Stage": "Сцена",
  "Church workspace": "Рабочая область церкви",
  "Workspace menu": "Меню рабочей области",
  "Church workspace menu": "Меню рабочей области церкви",
  "Church website ↗": "Сайт церкви ↗",
  "My account": "Моя учётная запись",
  "Log out": "Выйти",
  "Plan a service": "План служения",
  "Prepare a sermon": "Подготовка проповеди",
  "Events": "События",
  "People": "Люди",
  "Songs": "Песни",
  "Sermons": "Проповеди",
  "Media": "Медиа",
  "Live translation": "Перевод в реальном времени",
  "+ New service": "+ Новое служение",
  "Service title": "Название служения",
  "Service date": "Дата служения",
  "Creating…": "Создание…",
  "Create service": "Создать служение",
  "Make a copy of the current service": "Создать копию текущего служения",
  "Current service": "Текущее служение",
  "Choose a service…": "Выберите служение…",
  "Refresh services": "Обновить список служений",
  "Status": "Статус",
  "Planning": "Подготовка",
  "Ready": "Готово",
  "Archived": "В архиве",
  "Cancelled": "Отменено",
  "Save sermon slides": "Сохранить слайды проповеди",
  "Save service": "Сохранить служение",
  "Open a service to save": "Откройте служение для сохранения",
  "Saving…": "Сохранение…",
  "Save checkpoint · Ctrl/Cmd+S · Right-click for version history": "Сохранить версию · Ctrl/Cmd+S · История версий по правой кнопке мыши",
  "Working…": "Выполнение…",
  "Draft kept locally · retry Save": "Черновик сохранён локально · повторите сохранение",
  "Unsaved · retry Save": "Не сохранено · повторите сохранение",
  "Waiting to save…": "Ожидание сохранения…",
  "Saved on this computer · sync conflict": "Сохранено на этом компьютере · конфликт синхронизации",
  "Saved on this computer · waiting to sync": "Сохранено на этом компьютере · ожидание синхронизации",
  "Saved on this computer": "Сохранено на этом компьютере",
  "All changes saved.": "Все изменения сохранены.",
  "Saved on this computer. Review the server conflict before syncing.": "Сохранено на этом компьютере. Проверьте конфликт с сервером перед синхронизацией.",
  "Saved on this computer. Waiting to sync.": "Сохранено на этом компьютере. Ожидание синхронизации.",
  "Previous version restored as a new version.": "Предыдущая версия восстановлена как новая.",
  "Manual checkpoint saved.": "Ручная версия сохранена.",
  "Version history": "История версий",
  "Preview previous versions. Restoring creates a new version and keeps this history.": "Просматривайте предыдущие версии. Восстановление создаёт новую версию и сохраняет историю.",
  "Back to editing": "Вернуться к редактированию",
  "← Back to editing": "← Вернуться к редактированию",
  "Saved versions": "Сохранённые версии",
  "Automatic save": "Автосохранение",
  "Restored version": "Восстановленная версия",
  "Manual save · Ctrl/Cmd+S": "Ручное сохранение · Ctrl/Cmd+S",
  "Saved version": "Сохранённая версия",
  "No saved versions yet.": "Сохранённых версий пока нет.",
  "Load earlier versions": "Загрузить более ранние версии",
  "Version preview": "Просмотр версии",
  "Choose a version": "Выберите версию",
  " · Current": " · Текущая",
  "Preview language": "Язык просмотра",
  "Restoring…": "Восстановление…",
  "Restore this version": "Восстановить эту версию",
  "Loading version…": "Загрузка версии…",
  "This version has no slides.": "В этой версии нет слайдов.",
  "Historical slide navigation": "Навигация по слайдам версии",
  "Previous slide": "Предыдущий слайд",
  "Next slide": "Следующий слайд",
  "0 slides": "0 слайдов",
  "Version {version}": "Версия {version}",
  "{count} saves": "Сохранений: {count}",
  "{count} slides": "Слайдов: {count}",
  "Slide settings": "Настройки слайда",
  "Slide settings…": "Настройки слайда…",
  "Close slide settings": "Закрыть настройки слайда",
  "Changes stay in your draft. Save the sermon or service to keep them.": "Изменения остаются в черновике. Сохраните проповедь или служение, чтобы сохранить их.",
  "Done": "Готово",
  "Cancel": "Отмена",
  "Delete": "Удалить",
  "Move": "Переместить",
  "Duplicate": "Дублировать",
  "Move To…": "Переместить…",
  "Close Move To": "Закрыть перемещение",
  "Close Delete": "Закрыть удаление",
  "Starting slide number": "Начальный номер слайда",
  "The selection will start at this number. Its slides stay in order; the other slides shift to make room.": "Выделенные слайды начнутся с этого номера и сохранят порядок. Остальные слайды сместятся.",
  "Could not move the slides.": "Не удалось переместить слайды.",
  "The selected sections and their slides will be removed from this service.": "Выбранные разделы и их слайды будут удалены из служения.",
  "The selected slides will be removed from this service.": "Выбранные слайды будут удалены из служения.",
  "Library originals stay unchanged.": "Оригиналы в библиотеке не изменятся.",
  "Undo restores the whole selection before you save.": "До сохранения команда «Отменить» восстанавливает все выделенные слайды.",
  "Move {selection} to…": "Переместить {selection}…",
  "Delete {selection}?": "Удалить {selection}?",
  "slide": "слайд",
  "section": "раздел",
  "1 slide": "1 слайд",
  "Choose 1–{maximum}": "Выберите от 1 до {maximum}",
  "The selection occupies {count} consecutive slides.": "Выделение занимает {count} последовательных слайдов.",
  "Change Bible edition to {edition}?": "Заменить перевод Библии на {edition}?",
  "Close Bible edition change": "Закрыть замену перевода Библии",
  "This replaces edited Scripture wording and highlights on the {output} output for this passage. Other passages and the other language stay unchanged.": "Это заменит отредактированный текст Писания и выделения в этом отрывке на экране «{output}». Другие отрывки и другой язык не изменятся.",
  "Undo restores the previous wording and formatting before you save.": "До сохранения команда «Отменить» восстанавливает прежний текст и оформление.",
  "Change edition": "Заменить перевод",
  "Service Preview": "Просмотр служения",
  "Sermon preview": "Просмотр проповеди",
  "All slides": "Все слайды",
  "Thumbnail output": "Экран миниатюр",
  "Thumbnail size": "Размер миниатюр",
  "Smaller thumbnails": "Уменьшить миниатюры",
  "Larger thumbnails": "Увеличить миниатюры",
  "Slide tiles": "Миниатюры слайдов",
  "Blank": "Пустой",
  "Hidden": "Скрыт",
  "No slides in this service yet.": "В этом служении пока нет слайдов.",
  "Rehearsal controls": "Управление репетицией",
  "Unsaved draft": "Несохранённый черновик",
  "Saved service": "Сохранённое служение",
  "Preview only": "Только просмотр",
  "Slide": "Слайд",
  "No slide selected": "Слайд не выбран",
  "Next:": "Далее:",
  "End of service": "Конец служения",
  "Preview navigation": "Навигация в просмотре",
  "← Previous": "← Предыдущий",
  "Next →": "Следующий →",
  "← / → or Space to navigate.": "← / → или пробел для перехода.",
  "Double-click a tile to edit it.": "Дважды нажмите на миниатюру для редактирования.",
  "Selected output previews": "Просмотр выбранных экранов",
  "Preview slide {number}: {title}": "Просмотр слайда {number}: {title}",
  "{label} output": "Экран «{label}»",
  "Sermon": "Проповедь",
  "Sermon to prepare": "Проповедь для подготовки",
  "Choose a sermon…": "Выберите проповедь…",
  "New sermon": "Новая проповедь",
  "More": "Ещё",
  "Refresh sermons": "Обновить список проповедей",
  "Create from manuscript and passages": "Создать из рукописи и отрывков",
  "Start a private draft, then build its slides. Publication can be reviewed later.": "Начните с личного черновика, затем создайте слайды. Публикацию можно проверить позже.",
  "Title": "Название",
  "Speaker": "Проповедник",
  "Primary language": "Основной язык",
  "Create and edit slides": "Создать и редактировать слайды",
  "Back to sermon slides": "Вернуться к слайдам проповеди",
  "Build the sermon’s slides here": "Подготовьте слайды проповеди здесь",
  "Choose a sermon on the left, or create one. Add Bible passages, main points, quotations, pictures, and video. Preview English, Russian, and the stage screen as you work.": "Выберите проповедь слева или создайте новую. Добавляйте отрывки Библии, основные мысли, цитаты, изображения и видео. Проверяйте английский, русский и сценический экраны во время работы.",
  "After saving, open Plan a service → Sermon → Add whole sermon.": "После сохранения откройте «План служения» → «Проповедь» → «Добавить всю проповедь».",
  "Your current slides could not be saved. Keep this sermon open and try saving again.": "Не удалось сохранить текущие слайды. Оставьте проповедь открытой и повторите сохранение.",
  "Could not open the sermon workspace.": "Не удалось открыть рабочую область проповеди.",
  "Sermon slides": "Слайды проповеди",
  "Service order": "Порядок служения",
  "＋ Add slide": "＋ Добавить слайд",
  "Add a slide": "Добавить слайд",
  "Add slides": "Добавление слайдов",
  "Add slide palette": "Панель добавления слайдов",
  "Close add slide palette": "Закрыть панель добавления слайдов",
  "Service planner": "План служения",
  "Build your service": "Подготовьте служение",
  "Inside sermon": "Внутри проповеди",
  "Select a section to open its slides · Ctrl/⌘: one slide": "Выберите раздел, чтобы открыть его слайды · Ctrl/⌘: один слайд",
  "Section start: selects all · Ctrl/⌘: one slide": "Начало раздела: выбрать всё · Ctrl/⌘: один слайд",
  "select to expand": "нажмите для раскрытия",
  "slides ·": "слайдов ·",
  "▶ Start Translate": "▶ Начать перевод",
  "■ Stop Translate": "■ Остановить перевод",
  "Start Translate": "Начать перевод",
  "Stop Translate": "Остановить перевод",
  "Add a section, song, reading, or slide.": "Добавьте раздел, песню, чтение или слайд.",
  "No service open.": "Служение не открыто.",
  "Slide actions": "Действия со слайдом",
  "Section": "Раздел",
  "Restore original passage text": "Восстановить исходный текст отрывка",
  "Edit Translation Settings…": "Настройки перевода…",
  "Remove translation cue": "Удалить команду перевода",
  "Preview output": "Экран просмотра",
  "Screen:": "Экран:",
  "Undo": "Отменить",
  "Undo (Ctrl+Z / Command+Z)": "Отменить (Ctrl+Z / Command+Z)",
  "Hidden on this screen": "Скрыт на этом экране",
  "Intentional blank screen": "Пустой экран",
  "Save the service to preview this new media file.": "Сохраните служение, чтобы просмотреть новый медиафайл.",
  "Choose a numbered slide on the left.": "Выберите пронумерованный слайд слева.",
  "Preview unavailable:": "Просмотр недоступен:",
  "Choose a slide on the left": "Выберите слайд слева",
  "Choose a service to begin": "Выберите служение для начала",
  "Text layout": "Расположение текста",
  "Reading template": "Шаблон чтения",
  "Centered title": "Название по центру",
  "Pre-sermon": "Перед проповедью",
  "Apply alignment to": "Применить выравнивание к",
  "Alignment field": "Поле выравнивания",
  "Text": "Текст",
  "Heading": "Заголовок",
  "Author / source": "Автор / источник",
  "Text alignment": "Выравнивание текста",
  "Song font size": "Размер текста песни",
  "Reading font size": "Размер текста чтения",
  "Text size": "Размер текста",
  "Fitted size:": "Подобранный размер:",
  "across all pages.": "на всех страницах.",
  "One size for the whole song. Long lines can reduce it by up to 25%.": "Один размер для всей песни. Длинные строки могут уменьшить его до 25%.",
  "Remember for this song": "Запомнить для этой песни",
  "Whole verses move between pages to fit this size. Both languages stay together.": "Целые стихи перемещаются между страницами под этот размер. Оба языка остаются вместе.",
  "Reflow pages": "Переразбить страницы",
  "Slide objects": "Объекты слайда",
  "Copy layout to all outputs": "Скопировать расположение на все экраны",
  "Replace the objects on the other outputs with this slide layout?": "Заменить объекты на других экранах расположением этого слайда?",
  "Service / sermon topic": "Тема служения / проповеди",
  "Welcome slide topic": "Тема приветственного слайда",
  "Item name": "Название элемента",
  "Notes for the operator": "Заметки для оператора",
  "Show next-slide hints for this sermon": "Показывать подсказки следующего слайда для этой проповеди",
  "Applies to the title, points, quotations, and passages in this sermon.": "Применяется к названию, тезисам, цитатам и отрывкам этой проповеди.",
  "Song credit · bottom right of title slide": "Авторство песни · внизу справа на титульном слайде",
  "Song credit": "Авторство песни",
  "Replace title image": "Заменить изображение титульного слайда",
  "Uploading…": "Загрузка…",
  "Replace on every output": "Заменить на всех экранах",
  "Image description": "Описание изображения",
  "Attribution": "Источник / авторство",
  "Audio output": "Вывод звука",
  "Visual preset": "Шаблон оформления",
  "Section type": "Тип раздела",
  "Clear": "Очистить",
  "Primary language for this slide": "Основной язык этого слайда",
  "Song default ·": "Настройка песни ·",
  "Show translated song title": "Показывать перевод названия песни",
  "Show second language beneath title": "Показывать второй язык под названием",
  "Stacked translation": "Перевод под основным текстом",
  "Show translated lyrics · whole song": "Показывать перевод текста · вся песня",
  "Show title text": "Показывать название",
  "Darken image": "Затемнить изображение",
  "Song default primary language": "Основной язык песни по умолчанию",
  "Individual slide choices stay in place.": "Настройки отдельных слайдов сохраняются.",
  "Exact Community revisions stay pinned. Output-specific language choices live here so they do not clutter normal planning.": "Точные версии из Community закреплены. Настройки языка каждого экрана находятся здесь, чтобы не загромождать подготовку.",
  "Pinned exact lyrics": "Закреплённый точный текст песни",
  "Normal lyrics from": "Обычный текст из",
  "Current + next from": "Текущий и следующий текст из",
  "Fit": "Размещение",
  "Show on": "Показывать на",
  "· audio": "· звук",
  "This reading keeps exact translation text and checksums. Use Add slide → Scripture if the passage changes.": "Чтение сохраняет точный текст перевода и контрольные суммы. Если отрывок изменился, используйте «Добавить слайд» → «Писание».",
  "Open sermon publication review": "Открыть проверку публикации проповеди",
  "Full primary-language slide · Same-size next line, fitted to the available width.": "Полный слайд на основном языке · Следующая строка того же размера подгоняется по ширине.",
  "Click Scripture to edit this slide · Add omissions or [context] · Original Bible text is preserved.": "Нажмите на текст Писания для редактирования · Добавляйте пропуски или [контекст] · Исходный библейский текст сохраняется.",
  "Same stack on both audience screens · White primary language, orange translation · Click either to edit.": "Оба языка на экранах аудитории · Основной язык белым, перевод оранжевым · Нажмите на текст для редактирования.",
  "Click directly on the slide to edit · Select text for formatting · Empty guides are not projected.": "Нажмите на слайд для редактирования · Выделите текст для оформления · Пустые подсказки не выводятся на экран.",
  "Picture slide. Open Add slide → Media to replace its image.": "Слайд с изображением. Для замены откройте «Добавить слайд» → «Медиа».",
  "Click the slide text to edit · Click outside to apply · Save to keep changes": "Нажмите на текст слайда для редактирования · Нажмите вне поля для применения · Сохраните изменения",
  "The video opens paused. First Right or Space plays it; Space pauses or resumes; Right advances to the next service item.": "Видео открывается на паузе. → или пробел запускает его; пробел ставит на паузу или продолжает; → переходит к следующему элементу.",
  "Scripture": "Писание",
  "□ Blank slide": "□ Пустой слайд",
  "≡ Section divider": "≡ Разделитель разделов",
  "Song library": "Библиотека песен",
  "Sermon passage": "Отрывок проповеди",
  "Scripture reading": "Чтение Писания",
  "Media and reusable slides": "Медиа и сохранённые слайды",
  "Build your sermon": "Подготовьте проповедь",
  "Media & reusable slides": "Медиа и сохранённые слайды",
  "Choose a starting point, then edit the slide on the canvas.": "Выберите основу, затем отредактируйте слайд на холсте.",
  "Search in either language. Select a song to see its first section.": "Ищите на любом языке. Выберите песню, чтобы увидеть её первый раздел.",
  "The current sermon heading stays above your passage.": "Текущий заголовок проповеди остаётся над отрывком.",
  "Add a title, verse pages and a blank as one reading section.": "Добавьте название, страницы со стихами и пустой слайд как один раздел чтения.",
  "Use a saved slide, or add a picture or video.": "Используйте сохранённый слайд или добавьте изображение либо видео.",
  "Or add a prepared sermon": "Или добавьте готовую проповедь",
  "Saved sermon · newest first": "Сохранённая проповедь · сначала новые",
  "Prepared sermon": "Готовая проповедь",
  "Add whole sermon": "Добавить всю проповедь",
  "Copies all saved slides, media and notes into a new sermon section.": "Копирует все сохранённые слайды, медиа и заметки в новый раздел проповеди.",
  "Prepare a sermon ↗": "Подготовить проповедь ↗",
  "Find a song": "Найти песню",
  "English or Russian title…": "Название на английском или русском…",
  "Song language filter": "Фильтр языка песен",
  "All": "Все",
  "Community songs": "Песни Community",
  "No matching songs. Try another title or language.": "Песни не найдены. Попробуйте другое название или язык.",
  "Refresh library": "Обновить библиотеку",
  "Blank screen": "Пустой экран",
  "Stage keeps the next-slide cue": "На сцене остаётся подсказка следующего слайда",
  "Starts every new service": "В начале каждого нового служения",
  "Remove from Media": "Удалить из Медиа",
  "Save selected slide in Media": "Сохранить выбранный слайд в Медиа",
  "Slide name": "Название слайда",
  "Add at the beginning of every new service": "Добавлять в начало каждого нового служения",
  "Save reusable slide": "Сохранить для повторного использования",
  "Pictures and videos": "Изображения и видео",
  "Media stays private inside this service until its exact revision is opened in SyncShow.": "Медиа остаётся внутри этого служения, пока его точная версия не будет открыта в SyncShow.",
  "Add picture": "Добавить изображение",
  "Add video": "Добавить видео",
  "Replace": "Заменить",
  "Reading title template": "Шаблон названия чтения",
  "Centered reading title": "Название чтения по центру",
  "Pre-sermon · passage and service topic": "Перед проповедью · отрывок и тема служения",
  "English screen translation": "Перевод на английском экране",
  "Russian / stage screen translation": "Перевод на русском / сценическом экране",
  "Choose book and verses": "Выбрать книгу и стихи",
  "Book": "Книга",
  "Chapter": "Глава",
  "From": "С",
  "To": "По",
  "Fetching passage…": "Загрузка отрывка…",
  "Add sermon passage →": "Добавить отрывок проповеди →",
  "Add reading →": "Добавить чтение →",
  "Selected song": "Выбранная песня",
  "First section": "Первый раздел",
  "Song preview output": "Экран просмотра песни",
  "Choose a song": "Выберите песню",
  "Uses the song’s saved language and arrangement, including repeats.": "Использует сохранённый язык и порядок песни, включая повторы.",
  "Adding…": "Добавление…",
  "Add song to service →": "Добавить песню в служение →",
  "Adds the whole song and its ending blank.": "Добавляет всю песню и пустой слайд после неё.",
  "English screen": "Английский экран",
  "Russian / stage screen": "Русский / сценический экран",
  "Russian / stage": "Русский / сцена",
  "Bible translation": "Перевод Библии",
  "Mixed translations": "Разные переводы",
  "Changes every page of this passage.": "Изменяет все страницы этого отрывка.",
  "Changes this passage.": "Изменяет этот отрывок.",
  "Other passages stay unchanged.": "Другие отрывки не изменятся.",
  "Save this service to open translation settings.": "Сохраните служение, чтобы открыть настройки перевода.",
  "Translation settings ↗": "Настройки перевода ↗",
  "Choose a service or create the next one.": "Выберите служение или создайте новое.",
  "Recovered your unsaved local draft. Saving will resume.": "Несохранённый локальный черновик восстановлен. Сохранение продолжится.",
  "Section grouping and presentation layout updated. Save service to keep these changes.": "Группировка разделов и оформление обновлены. Сохраните служение, чтобы сохранить изменения.",
  "Service copied. The original service is unchanged.": "Служение скопировано. Исходное служение не изменилось.",
  "Slide copied into this service. Save when ready.": "Слайд скопирован в это служение. Сохраните, когда будете готовы.",
  "Saved in Media for future services.": "Сохранено в Медиа для будущих служений.",
  "This sermon has no saved slides yet. Open Prepare a sermon first.": "В проповеди пока нет сохранённых слайдов. Сначала откройте «Подготовка проповеди».",
  "Whole sermon added, including its saved slides and media. Save the service to keep it.": "Добавлена вся проповедь с её сохранёнными слайдами и медиа. Сохраните служение.",
  "Unsaved changes — output previews update immediately.": "Изменения не сохранены — просмотр экранов обновляется сразу.",
  "Size updated. Pages with edited wording keep their breaks so your excerpts stay intact.": "Размер обновлён. Страницы с отредактированным текстом сохраняют разбиение, чтобы отрывки остались целыми.",
  "Passage pages reflowed at this size. Both languages keep matching verse breaks. Undo restores the old layout.": "Страницы отрывка переразбиты под этот размер. Границы стихов совпадают на обоих языках. Команда «Отменить» вернёт прежнее расположение.",
  "Unsaved changes · Library originals are unchanged.": "Изменения не сохранены · Оригиналы в библиотеке не изменились.",
  "Unsaved changes · Undo restores the whole operation.": "Изменения не сохранены · Команда «Отменить» отменяет всю операцию.",
  "Change undone. Save when ready.": "Изменение отменено. Сохраните, когда будете готовы.",
  "Slide added. Click the placeholders on the slide to edit; guides are never projected.": "Слайд добавлен. Нажмите на поля слайда для редактирования; подсказки не выводятся на экран.",
  "This song is not linked to a Community library record.": "Эта песня не связана с записью библиотеки Community.",
  "Song layout saved. New services will reuse this size and alignment.": "Оформление песни сохранено. Новые служения будут использовать этот размер и выравнивание.",
  "This song has no reviewed document to pin.": "У песни нет проверенного документа для закрепления.",
  "Song pinned. One translation was not structurally aligned, so the reviewed primary version is used on that output until its arrangement is reviewed.": "Песня закреплена. Один перевод не совпадает по структуре, поэтому на этом экране используется проверенная основная версия до проверки перевода.",
  "Song pinned from Community with exact reviewed revisions. Save the shared service when the order is ready.": "Песня закреплена из Community с точными проверенными версиями. Сохраните служение, когда порядок будет готов.",
  "Fetching the selected Bible translation…": "Загрузка выбранного перевода Библии…",
  "The service changed while the translation was loading. Please choose the translation again.": "Служение изменилось во время загрузки перевода. Выберите перевод ещё раз.",
  "Translation updated for this passage. Verse selection and slide breaks are preserved. Save when ready; Undo restores the previous text.": "Перевод отрывка обновлён. Выбор стихов и границы слайдов сохранены. Сохраните, когда будете готовы; команда «Отменить» вернёт прежний текст.",
  "Translation unchanged.": "Перевод не изменился.",
  "Reading added as short, synchronized Scripture slides. Save service when ready.": "Чтение добавлено как короткие согласованные слайды Писания. Сохраните служение, когда будете готовы.",
  "Song output treatment changed while retaining the exact pinned library revisions.": "Вывод песни изменён; точные закреплённые версии библиотеки сохранены.",
  "Choose a PNG, JPEG, or WebP picture.": "Выберите изображение PNG, JPEG или WebP.",
  "Uploading the exact picture privately…": "Загрузка изображения…",
  "The target slide is no longer available.": "Выбранный слайд больше недоступен.",
  "Picture uploaded privately. Save the shared service to attach it to this revision.": "Изображение загружено. Сохраните служение, чтобы прикрепить его к этой версии.",
  "The service itself was not changed.": "Само служение не изменилось.",
  "Choose an MP4 or WebM video.": "Выберите видео MP4 или WebM.",
  "Uploading the exact video privately…": "Загрузка видео…",
  "Video uploaded privately. Save the shared service to attach it to this revision.": "Видео загружено. Сохраните служение, чтобы прикрепить его к этой версии.",
  "This document changed elsewhere. Your draft remains on this screen. Review the current server version before deciding what to keep.": "Документ изменён в другом месте. Ваш черновик остаётся на этом экране. Просмотрите текущую версию сервера, прежде чем выбрать, что сохранить.",
  "The current changes could not be saved.": "Не удалось сохранить текущие изменения.",
  "A recovered local draft differs from the server version.": "Восстановленный локальный черновик отличается от версии сервера.",
  "Recovered draft is open for review. Use Save to keep it as a new version.": "Восстановленный черновик открыт для просмотра. Нажмите «Сохранить», чтобы сохранить его как новую версию.",
  "Review recovered draft": "Просмотреть восстановленный черновик",
  "Review saved versions": "Просмотреть сохранённые версии",
  "Discard recovered draft": "Удалить восстановленный черновик",
  "Discard the recovered local draft? The saved server versions will remain in Version history.": "Удалить восстановленный локальный черновик? Сохранённые версии сервера останутся в истории версий.",
  "Local recovery storage is full or unavailable. Keep this page open until the server confirms your changes are saved.": "Локальное хранилище восстановления заполнено или недоступно. Оставьте страницу открытой, пока сервер не подтвердит сохранение изменений.",
  "Heritage Community could not complete that service change.": "Heritage Community не удалось применить изменение служения.",
  "Choose a PNG, JPEG, WebP, MP4, or WebM file.": "Выберите файл PNG, JPEG, WebP, MP4 или WebM.",
  "Choose a video no larger than 250 MB.": "Выберите видео размером до 250 МБ.",
  "Choose a picture no larger than 75 MB.": "Выберите изображение размером до 75 МБ.",
  "Workspace home": "Главная рабочей области",
  "Publish sermons": "Публикация проповедей",
  "Sermon library": "Библиотека проповедей",
  "Bible translations": "Переводы Библии",
  "Media library": "Библиотека медиа",
  "Restore as new version": "Восстановить как новую версию",
  "Open version history": "Открыть историю версий",
  "Main point": "Основная мысль",
  "Bible passage": "Отрывок Библии",
  "Quote / text": "Цитата / текст",
  "Other": "Другое",
  "Picture first · optional title and dimming": "Сначала изображение · название и затемнение по желанию",
  "Continue this sermon’s outline": "Продолжить план этой проповеди",
  "Exact verses with editable emphasis": "Точные стихи с редактируемыми выделениями",
  "A quotation or a single thought": "Цитата или отдельная мысль",
  "Move text, pictures and simple shapes": "Перемещайте текст, изображения и простые фигуры",
  "Uploading image…": "Загрузка изображения…",
  "Choose title image": "Выбрать изображение титульного слайда",
  "Sermon title": "Название проповеди",
  "Heading (optional)": "Заголовок (необязательно)",
  "Subtitle (optional)": "Подзаголовок (необязательно)",
  "Click to add your text": "Нажмите, чтобы добавить текст",
  "Author / source (optional)": "Автор / источник (необязательно)",
  "Add sub-point…": "Добавить подпункт…",
  "Add point…": "Добавить пункт…",
  "Add a sub-point": "Добавить подпункт",
  "Add slide object": "Добавить объект слайда",
  "Add text": "Добавить текст",
  "Add image": "Добавить изображение",
  "Add brace": "Добавить скобку",
  "Outline circle": "Контур круга",
  "Filled circle": "Заполненный круг",
  "Editing tips": "Советы по редактированию",
  "Select an object to move, resize or rotate it. Click inside text to type; select words to format them. Text shrinks to fit its box.": "Выберите объект для перемещения, изменения размера или поворота. Нажмите внутри текста для ввода; выделите слова для оформления. Размер текста подбирается под его рамку.",
  "Selected object properties": "Свойства выбранного объекта",
  "Left": "Слева",
  "Top": "Сверху",
  "Width": "Ширина",
  "Height": "Высота",
  "Rotation °": "Поворот °",
  "Object color": "Цвет объекта",
  "Font size (maximum)": "Размер текста (максимальный)",
  "Align": "Выравнивание",
  "left": "по левому краю",
  "center": "по центру",
  "right": "по правому краю",
  "Line width": "Толщина линии",
  "Filled": "Заполнить",
  "Bring forward": "На передний план",
  "Send backward": "На задний план",
  "Delete object": "Удалить объект",
  "Freeform slide": "Свободное расположение объектов",
  "Click to type": "Нажмите для ввода",
  "Slide image": "Изображение слайда",
  "Patterns on this device. Audience screens keep their colors. Text colors use patterned underlines; thin outlines use the dash samples below.": "Узоры применяются на этом устройстве. Экраны аудитории сохраняют цвета. Цвет текста обозначается узорным подчёркиванием; тонкие контуры — образцами штрихов ниже.",
  "Colors in this item": "Цвета этого элемента",
  "Used slide colors": "Используемые цвета слайда",
  "No added colors yet.": "Дополнительных цветов пока нет.",
  "Translation · slide": "Перевод · слайд",
  "Prepare audio on the previous slide. Translate from this slide until the next Stop Translate cue.": "Подготовьте звук на предыдущем слайде. Перевод идёт с этого слайда до следующей команды «Остановить перевод».",
  "Speaker’s language": "Язык говорящего",
  "English → Russian": "Английский → русский",
  "Russian → English": "Русский → английский",
  "Translated audio for phone listeners": "Звук перевода для слушателей на телефонах",
  "OpenAI realtime interpretation streams translated text and, when enabled, audio as the speaker talks. The interpreter supplies its own voice; a separate narration voice is not used.": "OpenAI передаёт перевод текста и, если включено, звука во время речи. Переводчик использует собственный голос; отдельный голос озвучивания не применяется.",
  "On-screen translation": "Перевод на экране",
  "Off": "Выключено",
  "Scrolling ticker · bottom 12%": "Бегущая строка · нижние 12%",
  "Appearing sentences · bottom 29%": "Появляющиеся предложения · нижние 29%",
  "Show translated text on": "Показывать текст перевода на",
  "Russian screen": "Русский экран",
  "Both audience screens": "Оба экрана аудитории",
  "Slide content ·": "Содержимое слайда ·",
  "% height": "% высоты",
  "Translation ·": "Перевод ·",
  "Slides keep their full width. This band takes space from the slide: text wraps and reduces in size only as needed to fit above it. Plan images and objects in the remaining area. The Stage-Facing Screen keeps its full layout.": "Слайды сохраняют полную ширину. Полоса занимает часть слайда: текст переносится и уменьшается только для размещения над ней. Располагайте изображения и объекты в оставшейся области. Сценический экран сохраняет полное расположение.",
  "Choose the mixer or computer audio source in SyncShow before the service. Save this service, then reload it in SyncShow.": "Перед служением выберите источник звука микшера или компьютера в SyncShow. Сохраните служение и загрузите его заново в SyncShow.",
  "Save translation cue": "Сохранить команду перевода",
  "Passage shortcut": "Быстрый ввод отрывка",
  "Primary passage shortcut": "Быстрый ввод основного отрывка",
  "Add each chapter as a separate reading.": "Добавляйте каждую главу отдельным чтением.",
  "Heritage shortcuts work here, including John 8:31-32,44.": "Здесь работают сокращения Heritage, например John 8:31-32,44.",
  "Use Heritage shortcuts, or choose the book and verses below.": "Используйте сокращения Heritage или выберите книгу и стихи ниже.",
  "Which book did you mean?": "Какую книгу вы имели в виду?",
  "Enter a book, chapter and verse, for example Joh 3:16 or 1 chr 3 7-10.": "Введите книгу, главу и стих, например Ин 3:16 или 1 chr 3 7-10.",
  "Scripture sources & copyright": "Источники Писания и авторские права",
  "Sermon preparation response is invalid.": "Ответ подготовки проповеди некорректен.",
  "Your Community sign-in expired. Sign in again, then return to Prepare a sermon.": "Сеанс Community истёк. Войдите снова и вернитесь в «Подготовка проповеди».",
  "Your current Community role cannot prepare sermons. Ask an owner, admin, or leader.": "Ваша роль в Community не позволяет готовить проповеди. Обратитесь к владельцу, администратору или руководителю.",
  "The Community server could not safely prepare this sermon. Try again without changing the form; the retry will reuse the same request identity.": "Сервер Community не смог подготовить проповедь. Повторите попытку, не меняя форму: будет использован тот же запрос.",
  "Sermon preparation response is not JSON.": "Ответ подготовки проповеди имеет неверный формат.",
  "This does not publish anything.": "Это ничего не публикует.",
  "Sermon prepared": "Проповедь подготовлена",
  "Existing result recovered": "Предыдущий результат восстановлен",
  "Private": "Личная",
  "record ·": "запись ·",
  "written section": "раздел текста",
  "written sections": "разделов текста",
  "confirmed other passage": "подтверждённый дополнительный отрывок",
  "confirmed other passages": "подтверждённых дополнительных отрывков",
  "Add it to a service plan": "Добавить в план служения",
  "Open publication review": "Открыть проверку публикации",
  "Prepare another sermon": "Подготовить другую проповедь",
  "Technical identity": "Технические сведения",
  "Service and speaker": "Служение и проповедник",
  "Faithful Prayer": "Верная молитва",
  "Pastor name": "Имя проповедника",
  "Use today": "Сегодня",
  "Content language": "Язык содержимого",
  "Use a language tag such as en or ru.": "Используйте код языка, например en или ru.",
  "Confirmed primary passage": "Подтверждённый основной отрывок",
  "Use the passage the congregation reads before this sermon. Exact verses let the Study Bible link the sermon back to this text.": "Укажите отрывок, который церковь читает перед проповедью. Точные стихи позволяют связать проповедь с этим текстом в Study Bible.",
  "Start chapter": "Начальная глава",
  "Start verse": "Начальный стих",
  "End chapter": "Последняя глава",
  "End verse": "Последний стих",
  "Other passages used in this sermon": "Другие отрывки этой проповеди",
  "No other passages have been added.": "Другие отрывки пока не добавлены.",
  "Remove": "Удалить",
  "Add another passage": "Добавить отрывок",
  "Reviewed sermon text": "Проверенный текст проповеди",
  "Paste at least one source. Line breaks are preserved; nothing is summarized or rewritten.": "Вставьте хотя бы один источник. Переносы строк сохраняются; текст не сокращается и не переписывается.",
  "Pastor's manuscript": "Рукопись проповедника",
  "Paste the pastor's sermon writeup here.": "Вставьте сюда рукопись проповеди.",
  "Slide notes": "Текст слайдов",
  "Paste the text intended for sermon slides here.": "Вставьте сюда текст для слайдов проповеди.",
  "Preparing sermon…": "Подготовка проповеди…",
  "Create private Ready sermon": "Создать личную готовую проповедь",
  "All changes saved · v{version}": "Все изменения сохранены · v{version}",
  "{count} selected": "Выбрано: {count}",
  "Slide {number}": "Слайд {number}",
  "Selected: slide {number} · {title}": "Выбрано: слайд {number} · {title}",
  "Click section start to select all · Ctrl/⌘-click for one slide · Shift-click for range · Right-click for actions": "Начало раздела: выбрать всё · Ctrl/⌘: один слайд · Shift: диапазон · Правая кнопка: действия",
  "Add “{action}” cue": "Добавить команду «{action}»",
  "Move up": "Переместить выше",
  "Move down": "Переместить ниже",
  "Change {channel} Scripture translation": "Заменить перевод Писания: {channel}",
  "Align {alignment}": "Выравнивание: {alignment}",
  "Replace {language} image": "Заменить изображение: {language}",
  "Choose {language} image": "Выбрать изображение: {language}",
  "Slide {number} {language} Scripture — click to edit": "Слайд {number}, {language}, Писание — нажмите для редактирования",
  "song": "песня",
  "reading": "чтение",
  "sermon": "проповедь",
  "fit": "вписать",
  "fill": "заполнить",
  "stretch": "растянуть",
  "{language} is not configured. Screens will show {fallback} content until you add text here.": "Текст на языке «{language}» не настроен. До его добавления экраны показывают содержимое на языке «{fallback}».",
  "the filled language": "заполненный язык",
  "“{title}” is a section, not a slide.": "«{title}» — раздел, а не слайд.",
  "{language} title for following passages": "Название для последующих отрывков: {language}",
  "Remove {title} from Media": "Удалить «{title}» из Медиа",
  "Text object {number}": "Текстовый объект {number}",
  "{kind} object {number}": "Объект {kind} {number}",
  "text": "текст",
  "image": "изображение",
  "brace": "скобка",
  "circle": "круг",
  "Move selected object": "Переместить выбранный объект",
  "Resize selected object": "Изменить размер выбранного объекта",
  "Rotate selected object": "Повернуть выбранный объект",
  "Service request failed ({status}).": "Не удалось выполнить запрос служения ({status}).",
  "Media upload failed ({status}).": "Не удалось загрузить медиа ({status}).",
  "Turn the pastor's reviewed manuscript or slide notes into one exact private sermon that can be selected in a service plan and read by SyncShow.": "Создайте точную личную проповедь из проверенной рукописи или текста слайдов. Её можно выбрать в плане служения и открыть в SyncShow.",
  "The pasted text and confirmed passage become a private Ready canonical record. This form does not upload or retain the original DOCX or PPTX file; keep that original in the church's normal records.": "Вставленный текст и подтверждённый отрывок станут личной готовой записью. Эта форма не загружает и не хранит исходный файл DOCX или PPTX; сохраните его в документах церкви.",
  "Optional. Add only passages the sermon actually cites or explains. Once reviewed and published, each one powers the Study Bible's small “Appears in sermons” link for those verses. Exact duplicates, including the primary passage, are safely collapsed.": "Необязательно. Добавляйте только отрывки, которые проповедь цитирует или объясняет. После проверки и публикации для них появится ссылка «Встречается в проповедях» в Study Bible. Совпадающие отрывки, включая основной, объединяются.",
  "I reviewed the title, speaker, date, primary passage, every other passage listed above, and the pasted text. Create one private Ready sermon for service planning.": "Я проверил название, проповедника, дату, основной и все дополнительные отрывки и вставленный текст. Создать одну личную готовую проповедь для плана служения.",
  "{count} of {maximum} added": "Добавлено {count} из {maximum}",
  "{count} selected slides": "Выбранных слайдов: {count}",
  "service": "служение",
  "point": "пункт",
  "subpoint": "подпункт",
  "custom": "пользовательский",
  "Selected text formatting": "Оформление выделенного текста",
  "Bold": "Полужирный",
  "Italic": "Курсив",
  "Underline": "Подчёркивание",
  "Text color": "Цвет текста",
  "Color": "Цвет",
  "Text highlight": "Выделение текста",
  "Highlight": "Выделение",
  "Remove highlight": "Убрать выделение",
  "No highlight": "Без выделения",
  "Clear formatting": "Убрать оформление",
  "Could not format text.": "Не удалось оформить текст.",
  "Red": "Красный",
  "Blue": "Синий",
  "Green": "Зелёный",
  "Yellow": "Жёлтый",
  "Orange": "Оранжевый",
  "Purple": "Фиолетовый",
  "Teal": "Бирюзовый",
  "White": "Белый",
  "Gray": "Серый",
  "Black": "Чёрный",
  "Dots": "Точки",
  "Horizontal waves": "Горизонтальные волны",
  "Vertical waves": "Вертикальные волны",
  "Diagonal lines": "Диагональные линии",
  "Horizontal lines": "Горизонтальные линии",
  "Crosses": "Крестики",
  "Vertical lines": "Вертикальные линии",
  "Small dots": "Мелкие точки",
  "{label} palette": "Палитра «{label}»"
}

export type WorkspaceTextVariables = Record<string, string | number>
export function translateWorkspaceText(value: string, language: WorkspaceLanguage, variables: WorkspaceTextVariables = {}) {
  const template = language === 'ru' ? russianWorkspaceText[value] || value : value
  return template.replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (match, name: string) => Object.hasOwn(variables, name) ? String(variables[name]) : match)
}
