import { test, expect } from '@playwright/test'
import catalog from '../src/data/audioCatalog.json' with { type: 'json' }
import timing from '../public/data/audio/books/martyrdom-of-polycarp.json' with { type: 'json' }
const book = catalog.books.find(book => book.id === 'martyrdom-of-polycarp')
const track = book.editions[0].tracks[0]
const wave = Buffer.alloc(44 + 300 * 8000 * 2)
wave.write('RIFF', 0); wave.writeUInt32LE(wave.length - 8, 4); wave.write('WAVEfmt ', 8)
wave.writeUInt32LE(16, 16); wave.writeUInt16LE(1, 20); wave.writeUInt16LE(1, 22)
wave.writeUInt32LE(8000, 24); wave.writeUInt32LE(16000, 28); wave.writeUInt16LE(2, 32); wave.writeUInt16LE(16, 34)
wave.write('data', 36); wave.writeUInt32LE(wave.length - 44, 40)
test.beforeEach(async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => { localStorage.setItem('heritage-translation', 'BSB'); localStorage.setItem('heritage-default-translation-v2', 'done') })
  await page.route(/https:\/\/(archive\.org\/download|openbible\.com\/audio)\//, route => {
    const range = route.request().headers().range?.match(/bytes=(\d+)-(\d*)/)
    const start = Number(range?.[1] || 0), end = range?.[2] ? Math.min(Number(range[2]), wave.length - 1) : wave.length - 1
    return route.fulfill({ status: range ? 206 : 200, contentType: 'audio/wav', body: wave.subarray(start, end + 1), headers: { 'Accept-Ranges': 'bytes', ...(range ? { 'Content-Range': `bytes ${start}-${end}/${wave.length}` } : {}) } })
  })
})
test('library groups Bible audio by translation and keeps book links reloadable', async ({ page }) => {
  await page.goto('/#/audio')
  await expect(page.getByRole('heading', { name: 'BSB Audio Bible', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Genesis', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Browse BSB books' }).click()
  await page.getByLabel('Search audio library').fill('Ezekiel')
  await expect(page.getByRole('heading', { name: 'Ezekiel', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Tracks and downloads' }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Play Ezekiel 42', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '← Bible books' }).click()
  await page.getByRole('button', { name: '← Translations' }).click()
  await expect(page.getByRole('heading', { name: 'BSB Audio Bible', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('audio-library-phone.png') })
})
test('quick settings are minimal; other preferences persist and stacking defaults on', async ({ page }) => {
  await page.goto('/#/genesis/1')
  await expect(page.locator('#verse-1-1')).toHaveJSProperty('tagName', 'SPAN')
  await page.getByTitle('Text size settings').click()
  for (const name of ['Audio Settings', 'Sync', 'Verse Stacking', 'Volume Scroll']) await expect(page.getByRole('button', { name, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await expect(page.getByLabel('Verse Stacking')).toBeHidden()
  await page.getByText('Other settings', { exact: true }).click()
  await expect(page.getByLabel('Verse Stacking')).toBeChecked()
  await page.getByLabel('Verse Stacking').uncheck()
  await page.getByLabel('B&W', { exact: true }).check()
  await page.getByLabel('Volume Scroll', { exact: true }).check()
  await page.reload()
  await expect(page.getByLabel('B&W', { exact: true })).toBeChecked()
  await expect(page.getByLabel('Volume Scroll', { exact: true })).toBeChecked()
  await page.getByText('Other settings', { exact: true }).click()
  await expect(page.getByLabel('Verse Stacking')).not.toBeChecked()
  await page.screenshot({ path: test.info().outputPath('more-settings-phone.png'), fullPage: true })
  await page.goto('/#/genesis/1')
  await expect(page.locator('#verse-1-1')).toHaveJSProperty('tagName', 'DIV')
})
for (const bible of [false, true]) test(`${bible ? 'Bible' : 'book'} play button opens controls on hold without toggling; timeline and ten-second controls work`, async ({ page }) => {
  const id = bible ? 'bsb-hays-01-001' : track.id
  await page.addInitScript(id => localStorage.setItem('heritage-audio-progress-v1', JSON.stringify({ lastTrackId: id, positions: { [id]: 45 }, rate: 1 })), id)
  await page.goto(bible ? '/#/genesis/1' : '/#/resources/books/martyrdom-of-polycarp-lake')
  const play = page.getByRole('button', { name: `Play ${bible ? 'chapter' : 'book'} audio`, exact: true })
  await play.click({ delay: 650 })
  const dialog = page.getByRole('dialog', { name: 'Player controls' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Rewind 10 seconds' }).click()
  await expect(dialog.getByLabel('Audio position', { exact: true })).toHaveValue('35')
  await dialog.getByRole('button', { name: 'Forward 10 seconds' }).click()
  await expect(dialog.getByLabel('Audio position', { exact: true })).toHaveValue('45')
  await dialog.getByLabel('Audio position', { exact: true }).fill('0')
  await expect(dialog.getByLabel('Audio position', { exact: true })).toHaveValue('0')
  await dialog.getByLabel('Audio position', { exact: true }).fill('45')
  await dialog.getByRole('button', { name: 'Play', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath(`${bible ? 'bible' : 'book'}-player-phone.png`) })
  await dialog.getByRole('button', { name: 'Close player' }).click()
  const pause = page.getByRole('button', { name: `Pause ${bible ? 'chapter' : 'book'} audio`, exact: true })
  await pause.press('Shift+Enter')
  await expect(dialog.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  if (!bible) {
    const rewind = page.getByRole('button', { name: 'Rewind 10 seconds', exact: true })
    await expect(rewind).toBeVisible()
    const before = await page.evaluate(id => JSON.parse(localStorage.getItem('heritage-audio-progress-v1')).positions[id], id)
    await rewind.click()
    await expect.poll(() => page.evaluate(id => JSON.parse(localStorage.getItem('heritage-audio-progress-v1')).positions[id], id)).toBeLessThan(before - 8)
  }
  await pause.click()
  await expect(play).toBeVisible()
  await expect(page.locator('.book-audio-rewind')).toHaveCount(0)
})
test('audiobook highlighting selects individual sentences without changing the paragraph text', async ({ page }) => {
  const spans = timing.tracks[track.id].sentenceSpans
  const first = spans.find((s, i) => s.start > 30 && s.end < 170 && spans[i + 1]?.paragraph === s.paragraph && spans[i + 1].textStart !== s.textStart)
  const second = spans[spans.indexOf(first) + 1]
  await page.addInitScript(({ id, at }) => localStorage.setItem('heritage-audio-progress-v1', JSON.stringify({ lastTrackId: id, positions: { [id]: at }, rate: 1 })), { id: track.id, at: first.start + .05 })
  await page.goto(`/#/resources/books/martyrdom-of-polycarp-lake?audioTrack=${track.id}&at=${first.start}`)
  await page.getByRole('button', { name: 'Play book audio' }).click({ delay: 650 })
  const dialog = page.getByRole('dialog', { name: 'Player controls' })
  const marker = page.locator('[data-audio-sentence="true"]')
  await expect(marker).toHaveText(timing.paragraphs[first.paragraph].text.slice(first.textStart, first.textEnd).replace(/\[\d+\]/g, ''))
  await dialog.getByLabel('Audio position', { exact: true }).fill(String(Math.ceil(second.start)))
  await dialog.getByRole('button', { name: 'Close player' }).click()
  await expect(marker).toHaveText(timing.paragraphs[second.paragraph].text.slice(second.textStart, second.textEnd).replace(/\[\d+\]/g, ''))
  await expect(marker.locator('..')).toHaveText(timing.paragraphs[second.paragraph].text.replace(/\[\d+\]/g, ''))
  await expect(marker.locator('..')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
})
