import { test, expect } from '@playwright/test'
async function enable(page) {
  await page.getByTitle('Enable parallel mode', { exact: true }).click()
  await page.getByRole('button', { name: 'Original languages', exact: true }).click()
  await page.getByRole('button', { name: /^Original Original languages/ }).click()
}
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('heritage-translation', 'BSB'); localStorage.setItem('heritage-default-translation-v2', 'done') })
})
test('Original switches between named Hebrew, Aramaic and Greek sources while navigating books', async ({ page }, testInfo) => {
  const errors=[]; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/genesis/1'); await enable(page)
  const source = page.locator('#verse-1-1 [data-translation="ORIGINAL"]').first()
  await expect(source).toContainText('בְּרֵאשִׁ֖ית')
  await expect(source).toHaveAttribute('dir', 'rtl')
  await page.evaluate(() => { location.hash = '/daniel/2' })
  await expect(page.locator('#verse-2-5 [data-translation="ORIGINAL"]').first()).toHaveAttribute('lang', 'arc')
  await expect(page.locator('#verse-2-4')).toContainText('Aramaic / Hebrew')
  await page.screenshot({ path: testInfo.outputPath('daniel-original.png') })
  await page.evaluate(() => { location.hash = '/romans/1' })
  await expect(page.locator('#verse-1-1 [data-translation="ORIGINAL"]').first()).toContainText('Παῦλος')
  await expect(page.locator('#verse-1-1 [data-translation="ORIGINAL"]').first()).toHaveAttribute('dir', 'ltr')
  await expect(page.getByLabel('Word links', { exact: true })).toBeVisible()
  await page.evaluate(() => { location.hash = '/genesis/32' })
  await expect(page.locator('#verse-32-1')).toContainText('WLC Gen.32.2')
  expect(errors).toEqual([])
})
test('Psalm headings and qere notes stay separate and phone Hebrew fits right to left', async ({ page }, testInfo) => {
  await page.setViewportSize({ width:390, height:844 })
  await page.goto('/#/psalms/51'); await enable(page)
  await expect(page.getByText('Hebrew source heading · Ps.51.1, Ps.51.2', { exact:true })).toBeVisible()
  await expect(page.locator('#verse-51-1')).toContainText('WLC Ps.51.3')
  await page.evaluate(() => { location.hash = '/daniel/1' })
  const row = page.locator('#verse-1-4')
  await row.getByText('Readings (qere)', { exact:true }).click()
  await expect(row).toContainText('Written:')
  await expect(row).toContainText('Read:')
  await expect(row.locator('[data-translation="ORIGINAL"]:visible')).toHaveAttribute('dir','rtl')
  await page.screenshot({ path:testInfo.outputPath('qere-phone.png') })
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1)).toBe(true)
  await page.evaluate(() => { location.hash = '/nehemiah/7' })
  await expect(page.locator('#verse-7-68')).toContainText('No text in the installed source.')
})
