import { test, expect } from '@playwright/test'
async function enable(page) {
  await page.goto('/#/romans/1')
  await page.getByTitle('Enable parallel mode', { exact: true }).click()
  await page.getByRole('button', { name: 'Original languages', exact: true }).click()
  await page.getByRole('button', { name: /^Original (Selected )?Original languages/ }).click()
}
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('heritage-translation', 'BSB'); localStorage.setItem('heritage-default-translation-v2', 'done') })
})
test('tap opens real Greek lemma occurrences; hold identifies the translation without opening notes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await enable(page)
  const servant = page.locator('#verse-1-1 [data-translation="BSB"] [data-word-link="1:1:1"]:visible').filter({ hasText: 'servant' })
  await expect(servant).toBeVisible()
  await servant.click()
  const dialog = page.getByRole('dialog', { name: 'Word study: servant' })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('δοῦλος (II) G1401')
  await expect(dialog).toContainText('Matthew')
  const example = dialog.getByRole('button', { name: /^Matthew 8:9/ })
  await expect(example.locator('[data-occurrence-translation=BSB]')).toContainText('BSB · “servant”')
  await expect(example.locator('[data-occurrence-translation=BSB] mark')).toHaveText('servant')
  await expect(example).toContainText('For I myself am a man under authority')
  await dialog.getByRole('button', { name: 'Close word study' }).click()
  await servant.click({ delay: 600 })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('δοῦλος ↔ a servant')
  await expect(page.locator('.bible-word-link-active:visible')).toHaveCount(3)
  await page.getByRole('button', { name: 'Clear word match' }).click()
  await servant.press('Shift+Enter')
  await expect(page.getByRole('status')).toContainText('δοῦλος ↔ a servant')
  await page.getByRole('button', { name: 'Clear word match' }).click()
  await page.getByTitle('Text size settings').click()
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await page.getByLabel('B&W', { exact: true }).check()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  // Re-enter session-only parallel mode after returning from settings.
  await enable(page)
  await expect(page.locator('.word-links-monochrome')).toBeVisible()
  await expect(servant).toHaveCSS('background-image', /M-1/)
  await page.screenshot({ path: test.info().outputPath('parallel-patterns-phone.png') })
  await page.reload()
  await page.getByTitle('Text size settings').click()
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await expect(page.getByLabel('B&W', { exact: true })).toBeChecked()
})
test('occurrence links navigate on the first click and unsupported matching remains explicit', async ({ page }) => {
  await enable(page)
  await page.locator('#verse-1-1 [data-translation="ORIGINAL"] [data-word-link="1:1:0"]:visible').click()
  const dialog = page.getByRole('dialog', { name: 'Word study: Παῦλος' })
  await expect(dialog).toContainText('Greek New Testament · Nestle 1904')
  await dialog.getByRole('button', { name: /^Acts 13:9/ }).click()
  await expect(page).toHaveURL(/#\/acts\/13$/)
  await expect(page.locator('#verse-13-9')).toBeInViewport()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  // The same source-backed lookup also works from English outside Romans,
  // even when the user disables the visual word-link colors.
  await page.getByLabel('Word links', { exact: true }).uncheck()
  const paul = page.locator('#verse-13-9 [data-translation="BSB"] [role="button"]:visible').filter({ hasText: /^Paul$/ })
  await paul.click()
  await expect(page.getByRole('dialog', { name: 'Word study: Paul' })).toContainText('Occurrences of the source lemma')
})

test('word occurrences show contextual translations on later pages and retain source verses on mapping failure', async ({ page }) => {
  await page.route('**/bsb-word-links/matthew.json', route => route.fulfill({ status: 503, body: 'Temporarily unavailable' }))
  const requested = []
  page.on('request', request => { if (request.url().includes('/bsb-word-links/')) requested.push(request.url()) })
  await enable(page)
  await page.locator('#verse-1-1 [data-translation="BSB"] [data-word-link="1:1:1"]:visible').filter({ hasText: 'servant' }).click()
  const dialog = page.getByRole('dialog', { name: 'Word study: servant' })
  const first = dialog.getByRole('button', { name: /^Matthew 8:9/ })
  await expect(dialog.getByRole('status')).toContainText('Some BSB wording or word mappings could not load')
  await expect(first).toContainText('For I myself am a man under authority')
  await expect(first).toContainText('Greek · N1904')
  await expect(first.locator('[data-occurrence-translation=BSB] mark')).toHaveCount(0)
  expect(requested.some(url => url.endsWith('/revelation.json'))).toBe(false)
  await page.unroute('**/bsb-word-links/matthew.json')
  await dialog.getByRole('button', { name: 'Retry translations' }).click()
  await expect(first.locator('[data-occurrence-translation=BSB] mark')).toHaveText('servant')
  const unmapped = dialog.getByRole('button', { name: /^Matthew 18:27/ })
  await expect(unmapped).toContainText('Exact word mapping unavailable')
  await expect(unmapped.locator('[data-occurrence-translation=BSB] mark')).toHaveCount(0)
  const romans = dialog.getByRole('button', { name: /^Romans 6:19/ })
  for (let pageNumber = 0; pageNumber < 5 && await romans.count() === 0; pageNumber++) {
    await dialog.getByRole('button', { name: 'Show more' }).click()
  }
  await expect(romans.locator('[data-occurrence-translation=BSB]')).toContainText('BSB · “in slavery”')
  await expect(romans.locator('[data-occurrence-translation=BSB] mark')).toHaveText(['in slavery', 'in slavery'])
  await page.screenshot({ path: test.info().outputPath('word-occurrence-translations.png') })
  await dialog.getByRole('button', { name: 'Close word study' }).click()
  await page.context().setOffline(true)
  await page.locator('#verse-1-1 [data-translation="BSB"] [data-word-link="1:1:1"]:visible').filter({ hasText: 'servant' }).click()
  await expect(dialog.getByRole('button', { name: /^Matthew 8:9/ }).locator('[data-occurrence-translation=BSB] mark')).toHaveText('servant')
})
