import { test, expect } from '@playwright/test'
async function enable(page) {
  await page.goto('/#/romans/1')
  await page.getByTitle('Enable parallel mode', { exact: true }).click()
  await page.getByRole('button', { name: 'Original languages', exact: true }).click()
  await page.getByRole('button', { name: /^Original Original languages/ }).click()
}
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('heritage-translation', 'BSB'); localStorage.setItem('heritage-default-translation-v2', 'done') })
})
test('tap opens real Greek lemma occurrences; hold identifies the translation without opening notes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await enable(page)
  const servant = page.locator('#verse-1-1 [data-translation="BSB"] [data-word-link="1:1:1"]:visible').filter({ hasText: 'servant' })
  await expect(servant).toBeVisible()
  await servant.click()
  const dialog = page.getByRole('dialog', { name: 'Word study: servant' })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('δοῦλος (II) G1401')
  await expect(dialog).toContainText('Matthew')
  await dialog.getByRole('button', { name: 'Close word study' }).click()
  await servant.click({ delay: 600 })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('δοῦλος ↔ a servant')
  await expect(page.locator('.bible-word-link-active:visible')).toHaveCount(3)
  await page.getByRole('button', { name: 'Clear word match' }).click()
  await servant.press('Shift+Enter')
  await expect(page.getByRole('status')).toContainText('δοῦλος ↔ a servant')
  await page.getByRole('button', { name: 'Clear word match' }).click()
  await page.getByTitle('Text size settings').click()
  await page.getByLabel('B&W word links').check()
  await expect(page.locator('.word-links-monochrome')).toBeVisible()
  await page.getByTitle('Text size settings').click()
  await expect(servant).toHaveCSS('background-image', /M-1/)
  await page.screenshot({ path: test.info().outputPath('parallel-patterns-phone.png') })
  await page.reload()
  // Parallel mode is intentionally session-only; the presentation preference persists.
  await page.getByTitle('Text size settings').click()
  await expect(page.getByLabel('B&W word links')).toBeChecked()
})
test('occurrence links navigate on the first click and unsupported matching remains explicit', async ({ page }) => {
  await enable(page)
  await page.locator('#verse-1-1 [data-translation="ORIGINAL"] [data-word-link="1:1:0"]:visible').click()
  const dialog = page.getByRole('dialog', { name: 'Word study: Παῦλος' })
  await expect(dialog).toContainText('Greek New Testament · Nestle 1904')
  await dialog.getByRole('button', { name: /^Acts 13:9/ }).click()
  await expect(page).toHaveURL(/#\/acts\/13$/)
  await expect(page.locator('#verse-13-9')).toBeInViewport()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
