import { expect, test } from '@playwright/test'

test('verse numbers are visible favorites on a phone', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/philippians/4')
  const button = page.getByTestId('verse-bookmark-12')
  await expect(button).toBeVisible()
  await expect(button).toHaveText('12')
  expect(await button.evaluate(element => getComputedStyle(element.querySelector('span')).fontSize)).toBe('18px')
  await button.click()
  await expect(button).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('heading', { name: 'On this passage', exact: true })).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('verse-number-phone.png') })
  await page.reload()
  await expect(page.getByTestId('verse-bookmark-12')).toHaveAttribute('aria-pressed', 'true')
})

test('books remember font size and exact word bookmarks on a black reading background', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('heritage-dark-mode', 'true'))
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/resources/books/martyrdom-of-polycarp')
  const paragraph = page.locator('[data-book-paragraph="0"]').first()
  await expect(paragraph).toBeVisible()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await expect(page.getByLabel('Reading font size', { exact: true })).toHaveCount(0)
  await page.locator('header').getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByLabel('Reading font size', { exact: true }).fill('20')
  await page.getByLabel('Reading font size', { exact: true }).press('Enter')
  await page.keyboard.press('Escape')
  expect(await paragraph.evaluate(element => getComputedStyle(element).fontSize)).toBe('20px')
  await page.evaluate(() => {
    const root = document.querySelector('[data-book-paragraph="0"]')
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
    const node = walker.nextNode()
    const match = node.textContent.match(/[A-Za-z]{4,}/)
    const range = document.createRange()
    range.setStart(node, match.index)
    range.setEnd(node, match.index + match[0].length)
    const selection = window.getSelection()
    selection.removeAllRanges(); selection.addRange(range)
    document.dispatchEvent(new Event('selectionchange'))
  })
  await expect(page.getByRole('region', { name: 'Selected book text actions' })).toBeVisible()
  await page.getByRole('button', { name: 'Bookmark place' }).click()
  await expect(page.getByText('Place bookmarked.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(paragraph).toBeVisible()
  expect(await paragraph.evaluate(element => getComputedStyle(element).fontSize)).toBe('20px')
  await page.locator('summary').filter({ hasText: 'Bookmarks in this book' }).click()
  await page.locator('details button').filter({ hasText: '“' }).click()
  await expect(page.locator('[data-bookmark-place]')).toBeVisible()
  await page.evaluate(() => document.documentElement.classList.add('dark'))
  const backgrounds = await paragraph.evaluate(element => {
    const colors = []
    while (element) { colors.push(getComputedStyle(element).backgroundColor); element = element.parentElement }
    return colors
  })
  expect(backgrounds).toContain('rgb(0, 0, 0)')
  expect(backgrounds).not.toContain('rgb(31, 41, 55)')
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('book-dark-phone.png') })
})


for (const translation of ['BSB','LSV']) test(`${translation} Philippians 4:12 has matching colors and Greek word study`, async ({ page }) => {
  await page.addInitScript(translation => {
    localStorage.setItem('heritage-translation', translation)
    localStorage.setItem('heritage-default-translation-v2', 'done')
  }, translation)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/philippians/4')
  await page.getByTitle('Enable parallel mode', { exact: true }).click()
  await page.getByRole('button', { name: 'Original languages', exact: true }).click()
  await page.getByRole('button', { name: /^Original (Selected )?Original languages/ }).click()
  const word = page.locator(`#verse-4-12 [data-translation="${translation}"] [data-word-link="4:12:13"]:visible`).first()
  await expect(word).toBeVisible()
  await expect(word).toHaveAttribute('data-word-pattern', '1')
  await word.press('Shift+Enter')
  await expect(page.getByRole('status')).toContainText('χορτάζεσθαι ↔')
  await expect(page.locator('#verse-4-12 .bible-word-link-active:visible')).not.toHaveCount(0)
  await page.getByRole('button', { name: 'Clear word match' }).click()
  await word.click()
  await expect(page.getByRole('dialog')).toContainText('G5526')
  await page.getByRole('button', { name: 'Close word study' }).click()
  await page.locator('#verse-4-12').scrollIntoViewIfNeeded()
  await page.evaluate(() => { localStorage.setItem('heritage-dark-mode', 'true'); document.documentElement.classList.add('dark') })
  await expect(page.locator('#verse-4-12')).toHaveCSS('background-color', 'rgb(0, 0, 0)')
  await page.screenshot({ path: test.info().outputPath(`${translation.toLowerCase()}-parallel-phone.png`) })
})

test('book sentence rows seek to the clicked recording position and follow its highlight', async ({ page }) => {
  const { default: catalog } = await import('../src/data/audioCatalog.json', { with: { type: 'json' } })
  const { default: timing } = await import('../public/data/audio/books/martyrdom-of-polycarp.json', { with: { type: 'json' } })
  const track = catalog.books.find(book => book.id === 'martyrdom-of-polycarp').editions[0].tracks[0]
  const spans = timing.tracks[track.id].sentenceSpans
  const first = spans.find((span, index) => span.start > 30 && span.end < 170 && spans[index + 1]?.paragraph === span.paragraph)
  const second = spans[spans.indexOf(first) + 1]
  const wave = Buffer.alloc(44 + 400 * 8000 * 2)
  wave.write('RIFF', 0); wave.writeUInt32LE(wave.length - 8, 4); wave.write('WAVEfmt ', 8)
  wave.writeUInt32LE(16, 16); wave.writeUInt16LE(1, 20); wave.writeUInt16LE(1, 22)
  wave.writeUInt32LE(8000, 24); wave.writeUInt32LE(16000, 28); wave.writeUInt16LE(2, 32); wave.writeUInt16LE(16, 34)
  wave.write('data', 36); wave.writeUInt32LE(wave.length - 44, 40)
  await page.route('https://archive.org/download/**', route => {
    const range = route.request().headers().range?.match(/bytes=(\d+)-(\d*)/)
    const start = Number(range?.[1] || 0), end = range?.[2] ? Math.min(Number(range[2]), wave.length - 1) : wave.length - 1
    return route.fulfill({ status: range ? 206 : 200, contentType: 'audio/wav', body: wave.subarray(start, end + 1), headers: { 'Accept-Ranges': 'bytes', ...(range ? { 'Content-Range': `bytes ${start}-${end}/${wave.length}` } : {}) } })
  })
  await page.addInitScript(({ id, at }) => localStorage.setItem('heritage-audio-progress-v1', JSON.stringify({ lastTrackId: id, positions: { [id]: at }, rate: 1 })), { id: track.id, at: first.start })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`/#/resources/books/martyrdom-of-polycarp-lake?audioTrack=${track.id}&at=${first.start}`)
  await page.getByLabel('Verse scroll mode').check()
  const target = page.locator(`[data-sentence-start="${second.start}"]`)
  await expect(target).toHaveClass(/reader-sentence-row/)
  await target.click()
  await expect(page.getByRole('button', { name: 'Pause book audio' })).toBeVisible()
  await expect(target).toHaveAttribute('data-audio-sentence', 'true')
  await expect.poll(() => page.evaluate(id => JSON.parse(localStorage.getItem('heritage-audio-progress-v1')).positions[id], track.id)).toBeGreaterThanOrEqual(second.start)
  await page.screenshot({ path: test.info().outputPath('book-sentences-phone.png') })
})
