const RUSSIAN_BOOK_NAMES = {
  Genesis: 'Бытие',
  Exodus: 'Исход',
  Leviticus: 'Левит',
  Numbers: 'Числа',
  Deuteronomy: 'Второзаконие',
  Joshua: 'Иисус Навин',
  Judges: 'Судьи',
  Ruth: 'Руфь',
  '1 Samuel': '1 Царств',
  '2 Samuel': '2 Царств',
  '1 Kings': '3 Царств',
  '2 Kings': '4 Царств',
  '1 Chronicles': '1 Паралипоменон',
  '2 Chronicles': '2 Паралипоменон',
  Ezra: 'Ездра',
  Nehemiah: 'Неемия',
  Esther: 'Есфирь',
  Job: 'Иов',
  Psalms: 'Псалтирь',
  Proverbs: 'Притчи',
  Ecclesiastes: 'Екклесиаст',
  'Song of Solomon': 'Песнь Песней',
  Isaiah: 'Исаия',
  Jeremiah: 'Иеремия',
  Lamentations: 'Плач Иеремии',
  Ezekiel: 'Иезекииль',
  Daniel: 'Даниил',
  Hosea: 'Осия',
  Joel: 'Иоиль',
  Amos: 'Амос',
  Obadiah: 'Авдий',
  Jonah: 'Иона',
  Micah: 'Михей',
  Nahum: 'Наум',
  Habakkuk: 'Аввакум',
  Zephaniah: 'Софония',
  Haggai: 'Аггей',
  Zechariah: 'Захария',
  Malachi: 'Малахия',
  Matthew: 'Матфея',
  Mark: 'Марка',
  Luke: 'Луки',
  John: 'Иоанна',
  Acts: 'Деяния',
  Romans: 'Римлянам',
  '1 Corinthians': '1 Коринфянам',
  '2 Corinthians': '2 Коринфянам',
  Galatians: 'Галатам',
  Ephesians: 'Ефесянам',
  Philippians: 'Филиппийцам',
  Colossians: 'Колоссянам',
  '1 Thessalonians': '1 Фессалоникийцам',
  '2 Thessalonians': '2 Фессалоникийцам',
  '1 Timothy': '1 Тимофею',
  '2 Timothy': '2 Тимофею',
  Titus: 'Титу',
  Philemon: 'Филимону',
  Hebrews: 'Евреям',
  James: 'Иакова',
  '1 Peter': '1 Петра',
  '2 Peter': '2 Петра',
  '1 John': '1 Иоанна',
  '2 John': '2 Иоанна',
  '3 John': '3 Иоанна',
  Jude: 'Иуды',
  Revelation: 'Откровение',
}

const UKRAINIAN_BOOK_NAMES = {
  Genesis: 'Буття',
  Exodus: 'Вихід',
  Leviticus: 'Левит',
  Numbers: 'Числа',
  Deuteronomy: 'Повторення Закону',
  Joshua: 'Ісус Навин',
  Judges: 'Судді',
  Ruth: 'Рут',
  '1 Samuel': '1 Самуїлова',
  '2 Samuel': '2 Самуїлова',
  '1 Kings': '1 Царів',
  '2 Kings': '2 Царів',
  '1 Chronicles': '1 Хронік',
  '2 Chronicles': '2 Хронік',
  Ezra: 'Ездри',
  Nehemiah: 'Неемії',
  Esther: 'Естер',
  Job: 'Йов',
  Psalms: 'Псалми',
  Proverbs: 'Приповісті',
  Ecclesiastes: 'Екклезіяст',
  'Song of Solomon': 'Пісня Пісень',
  Isaiah: 'Ісая',
  Jeremiah: 'Єремія',
  Lamentations: 'Плач Єремії',
  Ezekiel: 'Єзекіїль',
  Daniel: 'Даниїл',
  Hosea: 'Осія',
  Joel: 'Йоіл',
  Amos: 'Амос',
  Obadiah: 'Овдій',
  Jonah: 'Йона',
  Micah: 'Михей',
  Nahum: 'Наум',
  Habakkuk: 'Авакум',
  Zephaniah: 'Софонія',
  Haggai: 'Огій',
  Zechariah: 'Захарія',
  Malachi: 'Малахія',
  Matthew: 'Матвія',
  Mark: 'Марка',
  Luke: 'Луки',
  John: 'Івана',
  Acts: 'Дії',
  Romans: 'Римлян',
  '1 Corinthians': '1 Коринтян',
  '2 Corinthians': '2 Коринтян',
  Galatians: 'Галатів',
  Ephesians: 'Ефесян',
  Philippians: "Филип'ян",
  Colossians: 'Колосян',
  '1 Thessalonians': '1 Солунян',
  '2 Thessalonians': '2 Солунян',
  '1 Timothy': '1 Тимофія',
  '2 Timothy': '2 Тимофія',
  Titus: 'Тита',
  Philemon: 'Филимона',
  Hebrews: 'Євреїв',
  James: 'Якова',
  '1 Peter': '1 Петра',
  '2 Peter': '2 Петра',
  '1 John': '1 Івана',
  '2 John': '2 Івана',
  '3 John': '3 Івана',
  Jude: 'Юди',
  Revelation: "Об'явлення",
}

export function localizeBookName(bookName, translationCode) {
  if (!bookName) return bookName
  if (translationCode === 'UKRK') return UKRAINIAN_BOOK_NAMES[bookName] || bookName
  if (translationCode && translationCode.startsWith('SYNO')) return RUSSIAN_BOOK_NAMES[bookName] || bookName
  return bookName
}

