/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'community-sessions': CommunitySession;
    'community-auth-challenges': CommunityAuthChallenge;
    'community-auth-rate-limits': CommunityAuthRateLimit;
    communities: Community;
    memberships: Membership;
    'community-invites': CommunityInvite;
    media: Media;
    'reading-plans': ReadingPlan;
    songs: Song;
    'syncshow-song-member-shares': SyncshowSongMemberShare;
    'syncshow-song-public-links': SyncshowSongPublicLink;
    'syncshow-device-grants': SyncshowDeviceGrant;
    'syncshow-connections': SyncshowConnection;
    sermons: Sermon;
    'service-plans': ServicePlan;
    'service-documents': ServiceDocument;
    'syncshow-service-document-changes': SyncshowServiceDocumentChange;
    'syncshow-sermon-changes': SyncshowSermonChange;
    'syncshow-sermon-publications': SyncshowSermonPublication;
    'syncshow-sermon-publication-catalogs': SyncshowSermonPublicationCatalog;
    books: Book;
    commentaries: Commentary;
    'plan-cohorts': PlanCohort;
    'plan-notes': PlanNote;
    events: Event;
    'event-rsvps': EventRsvp;
    'encrypted-sync': EncryptedSync;
    'sync-devices': SyncDevice;
    'sync-records': SyncRecord;
    'sync-conflicts': SyncConflict;
    'sync-account-events': SyncAccountEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'community-sessions': CommunitySessionsSelect<false> | CommunitySessionsSelect<true>;
    'community-auth-challenges': CommunityAuthChallengesSelect<false> | CommunityAuthChallengesSelect<true>;
    'community-auth-rate-limits': CommunityAuthRateLimitsSelect<false> | CommunityAuthRateLimitsSelect<true>;
    communities: CommunitiesSelect<false> | CommunitiesSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'community-invites': CommunityInvitesSelect<false> | CommunityInvitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'reading-plans': ReadingPlansSelect<false> | ReadingPlansSelect<true>;
    songs: SongsSelect<false> | SongsSelect<true>;
    'syncshow-song-member-shares': SyncshowSongMemberSharesSelect<false> | SyncshowSongMemberSharesSelect<true>;
    'syncshow-song-public-links': SyncshowSongPublicLinksSelect<false> | SyncshowSongPublicLinksSelect<true>;
    'syncshow-device-grants': SyncshowDeviceGrantsSelect<false> | SyncshowDeviceGrantsSelect<true>;
    'syncshow-connections': SyncshowConnectionsSelect<false> | SyncshowConnectionsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    'service-plans': ServicePlansSelect<false> | ServicePlansSelect<true>;
    'service-documents': ServiceDocumentsSelect<false> | ServiceDocumentsSelect<true>;
    'syncshow-service-document-changes': SyncshowServiceDocumentChangesSelect<false> | SyncshowServiceDocumentChangesSelect<true>;
    'syncshow-sermon-changes': SyncshowSermonChangesSelect<false> | SyncshowSermonChangesSelect<true>;
    'syncshow-sermon-publications': SyncshowSermonPublicationsSelect<false> | SyncshowSermonPublicationsSelect<true>;
    'syncshow-sermon-publication-catalogs': SyncshowSermonPublicationCatalogsSelect<false> | SyncshowSermonPublicationCatalogsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    commentaries: CommentariesSelect<false> | CommentariesSelect<true>;
    'plan-cohorts': PlanCohortsSelect<false> | PlanCohortsSelect<true>;
    'plan-notes': PlanNotesSelect<false> | PlanNotesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-rsvps': EventRsvpsSelect<false> | EventRsvpsSelect<true>;
    'encrypted-sync': EncryptedSyncSelect<false> | EncryptedSyncSelect<true>;
    'sync-devices': SyncDevicesSelect<false> | SyncDevicesSelect<true>;
    'sync-records': SyncRecordsSelect<false> | SyncRecordsSelect<true>;
    'sync-conflicts': SyncConflictsSelect<false> | SyncConflictsSelect<true>;
    'sync-account-events': SyncAccountEventsSelect<false> | SyncAccountEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People who have signed in. Use Member invitations before their first sign-in; use Memberships to change an existing person’s church role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  /**
   * Most people should be Members. Church roles are managed separately under Memberships.
   */
  systemRole: 'system-admin' | 'member';
  magicLinkTokenHash?: string | null;
  magicLinkExpiresAt?: string | null;
  accountProtection: 'email' | 'strict-password';
  strictPasswordHash?: string | null;
  strictPasswordAlgorithm?: string | null;
  strictPasswordParams?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  syncGeneration: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-sessions".
 */
export interface CommunitySession {
  id: number;
  user: number | User;
  tokenHash: string;
  expiresAt: string;
  revokedAt?: string | null;
  deviceId?: string | null;
  deviceName?: string | null;
  platform?: string | null;
  emailVerifiedAt?: string | null;
  lastUsedAt?: string | null;
  syncGeneration: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-auth-challenges".
 */
export interface CommunityAuthChallenge {
  id: number;
  user: number | User;
  emailHash: string;
  tokenHash: string;
  purpose: 'sign-in' | 'reverify';
  flow: 'community' | 'sync';
  deviceId: string;
  deviceName: string;
  platform: string;
  requiresPassword: boolean;
  expiresAt: string;
  failedAttempts: number;
  consumedAt?: string | null;
  supersededAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-auth-rate-limits".
 */
export interface CommunityAuthRateLimit {
  id: number;
  bucketHash: string;
  attempts: number;
  resetAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The public name, description, logo, time zone, and joining policy for this Heritage Community.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communities".
 */
export interface Community {
  id: number;
  name: string;
  /**
   * Set during installation. Heritage uses this ID to recognize the same church after updates.
   */
  slug: string;
  description?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  /**
   * For example: America/Los_Angeles.
   */
  timeZone: string;
  /**
   * Invite-only prevents strangers from creating member accounts on a public server.
   */
  joinPolicy: 'invite' | 'open';
  allowDirectoryListing?: boolean | null;
  contentServerEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded artwork, documents, audio, video, scores, and other files used by published resources.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  community: number | Community;
  status?: ('draft' | 'published') | null;
  alt?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The role an existing account has in this church. New people should normally be added through Member invitations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  community: number | Community;
  user: number | User;
  role: 'owner' | 'admin' | 'leader' | 'member';
  joinedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email a one-time join link and allow that address to become a member of this church in Heritage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-invites".
 */
export interface CommunityInvite {
  id: number;
  /**
   * The church this person may join.
   */
  community: number | Community;
  email: string;
  /**
   * Optional. The member can change their display name later.
   */
  displayName?: string | null;
  /**
   * This sets Community API permissions. It does not create a separate web-admin password; manage admin logins under Users.
   */
  role: 'member' | 'leader' | 'admin';
  active: boolean;
  /**
   * Selected for a new invitation. Select it again later to send a fresh 15-minute join link.
   */
  sendEmailNow?: boolean | null;
  emailSentAt?: string | null;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ordered reading days made from Bible passages and optional contextual notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reading-plans".
 */
export interface ReadingPlan {
  id: number;
  community: number | Community;
  /**
   * Drafts stay in the admin. Published items appear in the public Heritage catalog.
   */
  status: 'draft' | 'published' | 'archived';
  title: string;
  /**
   * Filled automatically from the title when left blank. Change it only if the public link needs a different short name.
   */
  slug: string;
  description?: string | null;
  /**
   * Change this value when published day contents change so reader progress can be reconciled safely.
   */
  revision: string;
  /**
   * Days are numbered automatically in this order. Drag rows to reorder the plan.
   */
  days: {
    /**
     * Optional display label, such as “Creation” or “Week 1”.
     */
    label?: string | null;
    items: (ReadingPlanPassage | ReadingPlanNote)[];
    id?: string | null;
  }[];
  /**
   * Generated from the Plan days rows.
   */
  totalDays: number;
  planData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  authors?: string[] | null;
  license?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadingPlanPassage".
 */
export interface ReadingPlanPassage {
  /**
   * Use a Heritage reference such as “Genesis 1-3” or “John 3:16-21”.
   */
  passage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'planPassage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadingPlanNote".
 */
export interface ReadingPlanNote {
  /**
   * Stable short ID used to preserve completion when the note text changes.
   */
  key: string;
  title: string;
  text: string;
  sources?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'planNote';
}
/**
 * Bilingual song listings, lyrics, chords, files, and a plain-language rights record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs".
 */
export interface Song {
  id: number;
  community: number | Community;
  /**
   * Drafts stay in the admin. Published items appear in the public Heritage catalog.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Filled automatically from the title when left blank. Change it only if the public link needs a different short name.
   */
  slug: string;
  /**
   * Stable identity shared with SyncShow. It does not change when a title changes.
   */
  syncId: string;
  /**
   * Songs are never anonymous. Scheduled songs use the Community server clock.
   */
  visibility: 'private' | 'public' | 'scheduled-public';
  /**
   * Required for scheduled visibility.
   */
  publishAt?: string | null;
  syncVersion: number;
  syncDocuments:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  memberShareReceiptId?: string | null;
  memberShareReceiptVersion?: number | null;
  memberSharePreviousSongSyncVersion?: number | null;
  memberShareSongSyncVersion?: number | null;
  memberShareFamilyRevision?: string | null;
  memberShareReviewRevision?: string | null;
  memberShareVisibility?: string | null;
  memberSharePublishAt?: string | null;
  memberShareTimeZone?: string | null;
  memberShareValidThrough?: string | null;
  memberShareReviewedAt?: string | null;
  memberShareConfirmedAt?: string | null;
  memberShareRequestRevision?: string | null;
  memberShareReceiptRevision?: string | null;
  title: string;
  description?: string | null;
  russianTitle?: string | null;
  /**
   * Optional. Add one alternate title per row.
   */
  alternateTitles?: string[] | null;
  authors?: string[] | null;
  lyrics?: string | null;
  /**
   * Optional ChordPro-compatible guitar chords.
   */
  chordSheet?: string | null;
  russianLyrics?: string | null;
  /**
   * Optional ChordPro-compatible guitar chords.
   */
  russianChordSheet?: string | null;
  key?: string | null;
  tempo?: number | null;
  choirScores?: (number | Media)[] | null;
  recordings?: (number | Media)[] | null;
  /**
   * Informational only. Choosing an option does not block or unlock publishing.
   */
  rightsStatus:
    | 'needs-review'
    | 'metadata-only'
    | 'public-domain'
    | 'licensed'
    | 'permission-granted'
    | 'community-translation'
    | 'mixed';
  /**
   * The song’s CCLI ID, not your church’s CCLI license number. The church license number is configured once during server setup.
   */
  ccliNumber?: string | null;
  license?: string | null;
  copyright?: string | null;
  /**
   * For example: who translated it, where the church received it, or why it is believed to be public domain.
   */
  rightsNotes?: string | null;
  sourceUrl?: string | null;
  permissionUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable exact-family reviews authorizing lyrics for signed-in Community members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-song-member-shares".
 */
export interface SyncshowSongMemberShare {
  id: number;
  community: number | Community;
  song: number | Song;
  schemaVersion: number;
  receiptId: string;
  receiptVersion: number;
  songSyncId: string;
  previousSongSyncVersion: number;
  songSyncVersion: number;
  familyRevision: string;
  reviewRevision: string;
  visibility: 'public' | 'scheduled-public';
  publishAt?: string | null;
  timeZone: string;
  validThrough?: string | null;
  reviewedAt: string;
  confirmedAt: string;
  requestRevision: string;
  receiptRevision: string;
  reviewSource: string;
  auditSource: string;
  idempotencyKeyHash: string;
  requestHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Revocable anonymous links to immutable, separately reviewed song-family snapshots.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-song-public-links".
 */
export interface SyncshowSongPublicLink {
  id: number;
  community: number | Community;
  song: number | Song;
  schemaVersion: number;
  linkId: string;
  linkVersion: number;
  songSyncId: string;
  songSyncVersion: number;
  familyRevision: string;
  reviewRevision: string;
  label?: string | null;
  issuedAt: string;
  expiresAt?: string | null;
  /**
   * Set this once to revoke the anonymous link. It cannot be undone.
   */
  revokedAt?: string | null;
  snapshotChecksum: string;
  snapshotSource: string;
  reviewSource: string;
  auditSource: string;
  createIdempotencyKeyHash: string;
  createRequestHash: string;
  revokeIdempotencyKeyHash?: string | null;
  revokeRequestHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-device-grants".
 */
export interface SyncshowDeviceGrant {
  id: number;
  community: number | Community;
  requestedEmail: string;
  clientName: string;
  deviceId: string;
  deviceSecretHash: string;
  userCodeHash: string;
  codeChallenge: string;
  scopes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'approved' | 'denied' | 'cancelled' | 'consumed';
  expiresAt: string;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Approved SyncShow installations. Revoke a connection to stop its scoped song and sermon access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-connections".
 */
export interface SyncshowConnection {
  id: number;
  community: number | Community;
  user: number | User;
  grant: number | SyncshowDeviceGrant;
  clientName: string;
  tokenHash: string;
  scopes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  revokedAt?: string | null;
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages with a speaker, date, Scripture references, transcript, and optional recordings or files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  community: number | Community;
  /**
   * Drafts stay in the admin. Published items appear in the public Heritage catalog.
   */
  status: 'draft' | 'published' | 'archived';
  title: string;
  /**
   * Filled automatically from the title when left blank. Change it only if the public link needs a different short name.
   */
  slug: string;
  description?: string | null;
  speaker: string;
  preachedAt: string;
  /**
   * For example: John 3:16-21.
   */
  scripture?: string[] | null;
  transcript?: string | null;
  media?: (number | Media)[] | null;
  series?: string | null;
  syncId?: string | null;
  syncVersion?: number | null;
  syncCurrentDocumentSource?: string | null;
  syncCurrentRevision?: string | null;
  syncArchived?: boolean | null;
  syncPublicationStatus?: ('draft' | 'ready' | 'published' | 'archived') | null;
  syncVisibility?: ('private' | 'members' | 'unlisted' | 'public') | null;
  syncSourceObjects?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  syncChangedAt?: string | null;
  syncCreateIdempotencyKey?: string | null;
  syncCreateIdempotencyHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The ordered service outline SyncShow volunteers can open without changing it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans".
 */
export interface ServicePlan {
  id: number;
  community: number | Community;
  /**
   * Ready means every selected song and sermon pin was checked against its current SyncShow revision.
   */
  status: 'draft' | 'ready' | 'archived' | 'cancelled';
  serviceDate: string;
  /**
   * Use the venue’s local 24-hour time as HH:mm.
   */
  startTime: string;
  title: string;
  /**
   * Optional reminders such as communion, sound check, or volunteer handoff notes.
   */
  teamNotes?: string | null;
  /**
   * Add items in service order. Drag rows to reorder them.
   */
  entries: {
    entryId?: string | null;
    kind: 'section' | 'song' | 'scripture' | 'sermon';
    /**
     * The label volunteers will see in SyncShow.
     */
    title: string;
    /**
     * The saved plan pins this song’s exact current SyncShow version.
     */
    song?: (number | null) | Song;
    /**
     * Only canonical SyncShow sermons can be used in a Ready plan.
     */
    sermon?: (number | null) | Sermon;
    scripture?: {
      bookId:
        | 'Gen'
        | 'Exod'
        | 'Lev'
        | 'Num'
        | 'Deut'
        | 'Josh'
        | 'Judg'
        | 'Ruth'
        | '1Sam'
        | '2Sam'
        | '1Kgs'
        | '2Kgs'
        | '1Chr'
        | '2Chr'
        | 'Ezra'
        | 'Neh'
        | 'Esth'
        | 'Job'
        | 'Ps'
        | 'Prov'
        | 'Eccl'
        | 'Song'
        | 'Isa'
        | 'Jer'
        | 'Lam'
        | 'Ezek'
        | 'Dan'
        | 'Hos'
        | 'Joel'
        | 'Amos'
        | 'Obad'
        | 'Jonah'
        | 'Mic'
        | 'Nah'
        | 'Hab'
        | 'Zeph'
        | 'Hag'
        | 'Zech'
        | 'Mal'
        | 'Matt'
        | 'Mark'
        | 'Luke'
        | 'John'
        | 'Acts'
        | 'Rom'
        | '1Cor'
        | '2Cor'
        | 'Gal'
        | 'Eph'
        | 'Phil'
        | 'Col'
        | '1Thess'
        | '2Thess'
        | '1Tim'
        | '2Tim'
        | 'Titus'
        | 'Phlm'
        | 'Heb'
        | 'Jas'
        | '1Pet'
        | '2Pet'
        | '1John'
        | '2John'
        | '3John'
        | 'Jude'
        | 'Rev';
      startChapter: number;
      startVerse: number;
      endChapter: number;
      endVerse: number;
      /**
       * For example BSB, ESV, KJV, or the church’s configured translation ID.
       */
      translationId: string;
      /**
       * Optionally link this congregational reading to the exact sermon later in this service. Leave both fields empty for an unrelated Scripture item.
       */
      sermonReading?: {
        /**
         * The saved plan resolves this relationship to one later sermon row by its stable row ID.
         */
        sermon?: (number | null) | Sermon;
        /**
         * Usually leave blank: a sermon with one confirmed primary passage is selected automatically. Enter its stable reference ID only when the sermon has several confirmed primary passages.
         */
        referenceId?: string | null;
      };
    };
    resolvedSyncId?: string | null;
    resolvedSyncVersion?: number | null;
    resolvedRevision?: string | null;
    id?: string | null;
  }[];
  syncId: string;
  syncVersion: number;
  revision: string;
  documentSource: string;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Canonical storage for the visual Plan a service editor and SyncShow. Display routing stays on the venue computer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-documents".
 */
export interface ServiceDocument {
  id: number;
  community: number | Community;
  /**
   * Derived from the shared document.
   */
  title: string;
  /**
   * Used to create an empty English, Russian, and Media document. Later changes come from the shared editor.
   */
  serviceDate: string;
  /**
   * Ready approves only the currently saved revision. Any content edit returns the new revision to Planning.
   */
  status: 'planning' | 'ready' | 'archived' | 'cancelled';
  /**
   * Canonical HeritageServiceDocumentV1 source. The visual preparation editor replaces this technical view during the pilot.
   */
  documentSource: string;
  syncId: string;
  syncVersion: number;
  revision: string;
  changedAt: string;
  readyRevision?: string | null;
  readyAt?: string | null;
  lastIdempotencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-service-document-changes".
 */
export interface SyncshowServiceDocumentChange {
  id: number;
  community: number | Community;
  serviceDocument: number | ServiceDocument;
  syncId: string;
  syncVersion: number;
  revision: string;
  status: string;
  title: string;
  serviceDate: string;
  documentSource: string;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-sermon-changes".
 */
export interface SyncshowSermonChange {
  id: number;
  community: number | Community;
  sermon: number | Sermon;
  syncId: string;
  syncVersion: number;
  revision: string;
  documentSource: string;
  archived: boolean;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-sermon-publications".
 */
export interface SyncshowSermonPublication {
  id: number;
  community: number | Community;
  sermon: number | Sermon;
  schemaVersion: number;
  active: boolean;
  visibility: 'public';
  publicationVersion: number;
  publishedAt: string;
  withdrawnAt?: string | null;
  syncId: string;
  publicId: string;
  publicRevision: string;
  publishedDocumentSource: string;
  selectedBodyEntryIds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  selectedMediaIds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  detailChecksum: string;
  detailSource: string;
  catalogItemChecksum: string;
  catalogItemSource: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-sermon-publication-catalogs".
 */
export interface SyncshowSermonPublicationCatalog {
  id: number;
  community: number | Community;
  schemaVersion: number;
  generation: number;
  changedAt: string;
  checksum: string;
  source: string;
  passageIndexChecksum: string;
  passageIndexSource: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Readable books and study resources, with optional downloadable files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  community: number | Community;
  /**
   * Drafts stay in the admin. Published items appear in the public Heritage catalog.
   */
  status: 'draft' | 'published' | 'archived';
  title: string;
  /**
   * Filled automatically from the title when left blank. Change it only if the public link needs a different short name.
   */
  slug: string;
  description?: string | null;
  author: string;
  publishedYear?: number | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  files?: (number | Media)[] | null;
  license?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bible notes attached to a book, chapter, verse, or verse range.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commentaries".
 */
export interface Commentary {
  id: number;
  community: number | Community;
  /**
   * Drafts stay in the admin. Published items appear in the public Heritage catalog.
   */
  status: 'draft' | 'published' | 'archived';
  title: string;
  /**
   * Filled automatically from the title when left blank. Change it only if the public link needs a different short name.
   */
  slug: string;
  description?: string | null;
  author: string;
  book: string;
  chapter?: number | null;
  verseStart?: number | null;
  verseEnd?: number | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  license?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A dated group of members reading the same church-hosted Bible plan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-cohorts".
 */
export interface PlanCohort {
  id: number;
  community: number | Community;
  plan: number | ReadingPlan;
  name: string;
  startsOn: string;
  endsOn?: string | null;
  defaultNoteVisibility: 'shared' | 'private' | 'leaders';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-notes".
 */
export interface PlanNote {
  id: number;
  community: number | Community;
  cohort: number | PlanCohort;
  plan: number | ReadingPlan;
  day: number;
  author: number | User;
  visibility: 'shared' | 'private' | 'leaders';
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Church calendar items shown to signed-in members, with optional RSVP buttons and reminders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  community: number | Community;
  title: string;
  description?: string | null;
  startsAt: string;
  endsAt?: string | null;
  /**
   * For example: America/Los_Angeles.
   */
  timeZone: string;
  location?: string | null;
  url?: string | null;
  rsvpEnabled?: boolean | null;
  defaultReminderMinutes?: number | null;
  cancelled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member responses recorded from the Heritage app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps".
 */
export interface EventRsvp {
  id: number;
  community: number | Community;
  event: number | Event;
  user: number | User;
  response: 'going' | 'maybe' | 'not-going';
  guests?: number | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "encrypted-sync".
 */
export interface EncryptedSync {
  id: number;
  user: number | User;
  deviceId: string;
  schemaVersion: number;
  keyId: string;
  salt: string;
  iv: string;
  ciphertext: string;
  contentHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-devices".
 */
export interface SyncDevice {
  id: number;
  user: number | User;
  deviceId: string;
  friendlyName: string;
  platform: string;
  firstConnectedAt: string;
  lastSyncedAt?: string | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-records".
 */
export interface SyncRecord {
  id: number;
  user: number | User;
  recordType: string;
  recordId: string;
  schemaVersion: number;
  serverRevision: number;
  originDeviceId: string;
  deleted: boolean;
  clientUpdatedAt?: string | null;
  keyId: string;
  iv: string;
  authTag: string;
  ciphertext: string;
  contentHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-conflicts".
 */
export interface SyncConflict {
  id: number;
  user: number | User;
  recordType: string;
  recordId: string;
  schemaVersion: number;
  baseRevision: number;
  serverRevision: number;
  originDeviceId: string;
  deleted: boolean;
  clientUpdatedAt?: string | null;
  serverRecordMissing: boolean;
  keyId: string;
  iv: string;
  authTag: string;
  ciphertext: string;
  contentHash: string;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-account-events".
 */
export interface SyncAccountEvent {
  id: number;
  user: number | User;
  eventType: 'device-connected' | 'protection-changed' | 'device-revoked';
  deviceId?: string | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'community-sessions';
        value: number | CommunitySession;
      } | null)
    | ({
        relationTo: 'communities';
        value: number | Community;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'community-invites';
        value: number | CommunityInvite;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'reading-plans';
        value: number | ReadingPlan;
      } | null)
    | ({
        relationTo: 'songs';
        value: number | Song;
      } | null)
    | ({
        relationTo: 'syncshow-song-member-shares';
        value: number | SyncshowSongMemberShare;
      } | null)
    | ({
        relationTo: 'syncshow-song-public-links';
        value: number | SyncshowSongPublicLink;
      } | null)
    | ({
        relationTo: 'syncshow-device-grants';
        value: number | SyncshowDeviceGrant;
      } | null)
    | ({
        relationTo: 'syncshow-connections';
        value: number | SyncshowConnection;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'service-plans';
        value: number | ServicePlan;
      } | null)
    | ({
        relationTo: 'service-documents';
        value: number | ServiceDocument;
      } | null)
    | ({
        relationTo: 'syncshow-service-document-changes';
        value: number | SyncshowServiceDocumentChange;
      } | null)
    | ({
        relationTo: 'syncshow-sermon-changes';
        value: number | SyncshowSermonChange;
      } | null)
    | ({
        relationTo: 'syncshow-sermon-publications';
        value: number | SyncshowSermonPublication;
      } | null)
    | ({
        relationTo: 'syncshow-sermon-publication-catalogs';
        value: number | SyncshowSermonPublicationCatalog;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'commentaries';
        value: number | Commentary;
      } | null)
    | ({
        relationTo: 'plan-cohorts';
        value: number | PlanCohort;
      } | null)
    | ({
        relationTo: 'plan-notes';
        value: number | PlanNote;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-rsvps';
        value: number | EventRsvp;
      } | null)
    | ({
        relationTo: 'encrypted-sync';
        value: number | EncryptedSync;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  systemRole?: T;
  magicLinkTokenHash?: T;
  magicLinkExpiresAt?: T;
  accountProtection?: T;
  strictPasswordHash?: T;
  strictPasswordAlgorithm?: T;
  strictPasswordParams?: T;
  syncGeneration?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-sessions_select".
 */
export interface CommunitySessionsSelect<T extends boolean = true> {
  user?: T;
  tokenHash?: T;
  expiresAt?: T;
  revokedAt?: T;
  deviceId?: T;
  deviceName?: T;
  platform?: T;
  emailVerifiedAt?: T;
  lastUsedAt?: T;
  syncGeneration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-auth-challenges_select".
 */
export interface CommunityAuthChallengesSelect<T extends boolean = true> {
  user?: T;
  emailHash?: T;
  tokenHash?: T;
  purpose?: T;
  flow?: T;
  deviceId?: T;
  deviceName?: T;
  platform?: T;
  requiresPassword?: T;
  expiresAt?: T;
  failedAttempts?: T;
  consumedAt?: T;
  supersededAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-auth-rate-limits_select".
 */
export interface CommunityAuthRateLimitsSelect<T extends boolean = true> {
  bucketHash?: T;
  attempts?: T;
  resetAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communities_select".
 */
export interface CommunitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  website?: T;
  logo?: T;
  timeZone?: T;
  joinPolicy?: T;
  allowDirectoryListing?: T;
  contentServerEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  community?: T;
  user?: T;
  role?: T;
  joinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-invites_select".
 */
export interface CommunityInvitesSelect<T extends boolean = true> {
  community?: T;
  email?: T;
  displayName?: T;
  role?: T;
  active?: T;
  sendEmailNow?: T;
  emailSentAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reading-plans_select".
 */
export interface ReadingPlansSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  title?: T;
  slug?: T;
  description?: T;
  revision?: T;
  days?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              planPassage?: T | ReadingPlanPassageSelect<T>;
              planNote?: T | ReadingPlanNoteSelect<T>;
            };
        id?: T;
      };
  totalDays?: T;
  planData?: T;
  authors?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadingPlanPassage_select".
 */
export interface ReadingPlanPassageSelect<T extends boolean = true> {
  passage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReadingPlanNote_select".
 */
export interface ReadingPlanNoteSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  text?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs_select".
 */
export interface SongsSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  slug?: T;
  syncId?: T;
  visibility?: T;
  publishAt?: T;
  syncVersion?: T;
  syncDocuments?: T;
  memberShareReceiptId?: T;
  memberShareReceiptVersion?: T;
  memberSharePreviousSongSyncVersion?: T;
  memberShareSongSyncVersion?: T;
  memberShareFamilyRevision?: T;
  memberShareReviewRevision?: T;
  memberShareVisibility?: T;
  memberSharePublishAt?: T;
  memberShareTimeZone?: T;
  memberShareValidThrough?: T;
  memberShareReviewedAt?: T;
  memberShareConfirmedAt?: T;
  memberShareRequestRevision?: T;
  memberShareReceiptRevision?: T;
  title?: T;
  description?: T;
  russianTitle?: T;
  alternateTitles?: T;
  authors?: T;
  lyrics?: T;
  chordSheet?: T;
  russianLyrics?: T;
  russianChordSheet?: T;
  key?: T;
  tempo?: T;
  choirScores?: T;
  recordings?: T;
  rightsStatus?: T;
  ccliNumber?: T;
  license?: T;
  copyright?: T;
  rightsNotes?: T;
  sourceUrl?: T;
  permissionUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-song-member-shares_select".
 */
export interface SyncshowSongMemberSharesSelect<T extends boolean = true> {
  community?: T;
  song?: T;
  schemaVersion?: T;
  receiptId?: T;
  receiptVersion?: T;
  songSyncId?: T;
  previousSongSyncVersion?: T;
  songSyncVersion?: T;
  familyRevision?: T;
  reviewRevision?: T;
  visibility?: T;
  publishAt?: T;
  timeZone?: T;
  validThrough?: T;
  reviewedAt?: T;
  confirmedAt?: T;
  requestRevision?: T;
  receiptRevision?: T;
  reviewSource?: T;
  auditSource?: T;
  idempotencyKeyHash?: T;
  requestHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-song-public-links_select".
 */
export interface SyncshowSongPublicLinksSelect<T extends boolean = true> {
  community?: T;
  song?: T;
  schemaVersion?: T;
  linkId?: T;
  linkVersion?: T;
  songSyncId?: T;
  songSyncVersion?: T;
  familyRevision?: T;
  reviewRevision?: T;
  label?: T;
  issuedAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  snapshotChecksum?: T;
  snapshotSource?: T;
  reviewSource?: T;
  auditSource?: T;
  createIdempotencyKeyHash?: T;
  createRequestHash?: T;
  revokeIdempotencyKeyHash?: T;
  revokeRequestHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-device-grants_select".
 */
export interface SyncshowDeviceGrantsSelect<T extends boolean = true> {
  community?: T;
  requestedEmail?: T;
  clientName?: T;
  deviceId?: T;
  deviceSecretHash?: T;
  userCodeHash?: T;
  codeChallenge?: T;
  scopes?: T;
  status?: T;
  expiresAt?: T;
  approvedBy?: T;
  approvedAt?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-connections_select".
 */
export interface SyncshowConnectionsSelect<T extends boolean = true> {
  community?: T;
  user?: T;
  grant?: T;
  clientName?: T;
  tokenHash?: T;
  scopes?: T;
  expiresAt?: T;
  revokedAt?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  title?: T;
  slug?: T;
  description?: T;
  speaker?: T;
  preachedAt?: T;
  scripture?: T;
  transcript?: T;
  media?: T;
  series?: T;
  syncId?: T;
  syncVersion?: T;
  syncCurrentDocumentSource?: T;
  syncCurrentRevision?: T;
  syncArchived?: T;
  syncPublicationStatus?: T;
  syncVisibility?: T;
  syncSourceObjects?: T;
  syncChangedAt?: T;
  syncCreateIdempotencyKey?: T;
  syncCreateIdempotencyHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans_select".
 */
export interface ServicePlansSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  serviceDate?: T;
  startTime?: T;
  title?: T;
  teamNotes?: T;
  entries?:
    | T
    | {
        entryId?: T;
        kind?: T;
        title?: T;
        song?: T;
        sermon?: T;
        scripture?:
          | T
          | {
              bookId?: T;
              startChapter?: T;
              startVerse?: T;
              endChapter?: T;
              endVerse?: T;
              translationId?: T;
              sermonReading?:
                | T
                | {
                    sermon?: T;
                    referenceId?: T;
                  };
            };
        resolvedSyncId?: T;
        resolvedSyncVersion?: T;
        resolvedRevision?: T;
        id?: T;
      };
  syncId?: T;
  syncVersion?: T;
  revision?: T;
  documentSource?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-documents_select".
 */
export interface ServiceDocumentsSelect<T extends boolean = true> {
  community?: T;
  title?: T;
  serviceDate?: T;
  status?: T;
  documentSource?: T;
  syncId?: T;
  syncVersion?: T;
  revision?: T;
  changedAt?: T;
  readyRevision?: T;
  readyAt?: T;
  lastIdempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-service-document-changes_select".
 */
export interface SyncshowServiceDocumentChangesSelect<T extends boolean = true> {
  community?: T;
  serviceDocument?: T;
  syncId?: T;
  syncVersion?: T;
  revision?: T;
  status?: T;
  title?: T;
  serviceDate?: T;
  documentSource?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-sermon-changes_select".
 */
export interface SyncshowSermonChangesSelect<T extends boolean = true> {
  community?: T;
  sermon?: T;
  syncId?: T;
  syncVersion?: T;
  revision?: T;
  documentSource?: T;
  archived?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-sermon-publications_select".
 */
export interface SyncshowSermonPublicationsSelect<T extends boolean = true> {
  community?: T;
  sermon?: T;
  schemaVersion?: T;
  active?: T;
  visibility?: T;
  publicationVersion?: T;
  publishedAt?: T;
  withdrawnAt?: T;
  syncId?: T;
  publicId?: T;
  publicRevision?: T;
  publishedDocumentSource?: T;
  selectedBodyEntryIds?: T;
  selectedMediaIds?: T;
  detailChecksum?: T;
  detailSource?: T;
  catalogItemChecksum?: T;
  catalogItemSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syncshow-sermon-publication-catalogs_select".
 */
export interface SyncshowSermonPublicationCatalogsSelect<T extends boolean = true> {
  community?: T;
  schemaVersion?: T;
  generation?: T;
  changedAt?: T;
  checksum?: T;
  source?: T;
  passageIndexChecksum?: T;
  passageIndexSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  title?: T;
  slug?: T;
  description?: T;
  author?: T;
  publishedYear?: T;
  body?: T;
  files?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commentaries_select".
 */
export interface CommentariesSelect<T extends boolean = true> {
  community?: T;
  status?: T;
  title?: T;
  slug?: T;
  description?: T;
  author?: T;
  book?: T;
  chapter?: T;
  verseStart?: T;
  verseEnd?: T;
  body?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-cohorts_select".
 */
export interface PlanCohortsSelect<T extends boolean = true> {
  community?: T;
  plan?: T;
  name?: T;
  startsOn?: T;
  endsOn?: T;
  defaultNoteVisibility?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-notes_select".
 */
export interface PlanNotesSelect<T extends boolean = true> {
  community?: T;
  cohort?: T;
  plan?: T;
  day?: T;
  author?: T;
  visibility?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  community?: T;
  title?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  timeZone?: T;
  location?: T;
  url?: T;
  rsvpEnabled?: T;
  defaultReminderMinutes?: T;
  cancelled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps_select".
 */
export interface EventRsvpsSelect<T extends boolean = true> {
  community?: T;
  event?: T;
  user?: T;
  response?: T;
  guests?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "encrypted-sync_select".
 */
export interface EncryptedSyncSelect<T extends boolean = true> {
  user?: T;
  deviceId?: T;
  schemaVersion?: T;
  keyId?: T;
  salt?: T;
  iv?: T;
  ciphertext?: T;
  contentHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-devices_select".
 */
export interface SyncDevicesSelect<T extends boolean = true> {
  user?: T;
  deviceId?: T;
  friendlyName?: T;
  platform?: T;
  firstConnectedAt?: T;
  lastSyncedAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-records_select".
 */
export interface SyncRecordsSelect<T extends boolean = true> {
  user?: T;
  recordType?: T;
  recordId?: T;
  schemaVersion?: T;
  serverRevision?: T;
  originDeviceId?: T;
  deleted?: T;
  clientUpdatedAt?: T;
  keyId?: T;
  iv?: T;
  authTag?: T;
  ciphertext?: T;
  contentHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-conflicts_select".
 */
export interface SyncConflictsSelect<T extends boolean = true> {
  user?: T;
  recordType?: T;
  recordId?: T;
  schemaVersion?: T;
  baseRevision?: T;
  serverRevision?: T;
  originDeviceId?: T;
  deleted?: T;
  clientUpdatedAt?: T;
  serverRecordMissing?: T;
  keyId?: T;
  iv?: T;
  authTag?: T;
  ciphertext?: T;
  contentHash?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sync-account-events_select".
 */
export interface SyncAccountEventsSelect<T extends boolean = true> {
  user?: T;
  eventType?: T;
  deviceId?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}