// Editorial comparisons, not additions to the plan's historical-setting dates.
// Source selections and limits are documented in docs/PROPHECY-HISTORICAL-CONTEXT.md.
const ref = (label, book, chapter, verse = 1) => ({ label, book, chapter, verse })

export const prophecyHistoricalContext = {
  'ezekiel-egypt-oracles': {
    title: 'Proposed prophecy fulfillment · Egypt',
    introduction: 'Compare what the passages predict with later events and the limits of the evidence. A historical resemblance is not by itself proof that every part of a prophecy was fulfilled. The timeline above dates the settings reported in the book; the comparisons below do not change those dates or date the book’s final composition.',
    preparedBy: 'Heritage editorial notes · AI-assisted research',
    sourceCheckedOn: '2026-09-21',
    reviewStatus: 'Specialist review pending',
    entries: [
      {
        id: 'egypt-unreliable-ally',
        title: 'Egypt as an unreliable support for Judah',
        passages: [ref('Ezekiel 29:6–7', 'Ezekiel', 29, 6), ref('Ezekiel 30:20–26', 'Ezekiel', 30, 20)],
        oracleDate: 'Tenth and eleventh years of Jehoiachin’s exile; during Jerusalem’s final siege.',
        eventDate: 'During the siege, before Jerusalem’s fall',
        event: 'Pharaoh’s approaching army interrupts the Babylonian siege. Jeremiah warns that Egypt will withdraw and Babylon will return.',
        placement: 'Read beside Jeremiah 37–38, Ezekiel 24 and the siege-to-fall account in 2 Kings 25. This is contemporary background, not a later conquest of Egypt.',
        contextPassages: [ref('Jeremiah 37:5–10', 'Jeremiah', 37, 5), ref('Ezekiel 24:1–2', 'Ezekiel', 24), ref('2 Kings 25:1–7', '2 Kings', 25)],
        connection: 'Egypt’s inability to protect Judah helps explain the broken-support image and the warning against relying on Pharaoh.',
        evidence: 'Jeremiah describes the interruption and predicts Babylon’s return; Kings narrates Jerusalem’s eventual capture. These are biblical accounts, not an independent Egyptian campaign record.',
        limits: 'This comparison does not establish the later plunder, forty-year desolation or return described elsewhere in the Egypt oracles.',
        assessment: 'Biblical background',
        sourceIds: [],
      },
      {
        id: 'nebuchadnezzar-egypt-campaign',
        title: 'Nebuchadnezzar’s campaign against Egypt',
        passages: [ref('Ezekiel 29:17–20', 'Ezekiel', 29, 17), ref('Ezekiel 30:10–12', 'Ezekiel', 30, 10)],
        oracleDate: 'Ezekiel 29:17: exile year 27, month 1, day 1 (about 571 BC). Ezekiel 30:1–19 has no separate date heading.',
        eventDate: 'About 568/567 BC · Nebuchadnezzar’s 37th year',
        event: 'The fragmentary Babylonian tablet BM 33041 is catalogued as a report of an Egyptian campaign in the king’s 37th year.',
        placement: 'Later than both the temple vision dated to exile year 25 in Ezekiel 40:1 and the year-27 oracle inserted into Ezekiel 29. The campaign is not narrated as an event between Ezekiel 29 and 30.',
        contextPassages: [ref('Ezekiel 29:17', 'Ezekiel', 29, 17), ref('Ezekiel 40:1', 'Ezekiel', 40), ref('Jeremiah 43:8–13', 'Jeremiah', 43, 8)],
        connection: 'The named Babylonian king, Egypt and the later military action make this a proposed historical connection to the oracle’s promised campaign and spoils.',
        evidence: 'The museum identifies the campaign. Ouysook emphasizes how little can be recovered from the broken tablet. Kahn reconstructs a brief Babylonian foothold followed by Egyptian resistance from additional Egyptian evidence.',
        limits: 'The extent and result of the campaign are disputed. These sources do not securely establish the promised scale of plunder, nationwide devastation or every feature of Ezekiel 29–32. The connection is an editorial comparison, not an inscription identifying a fulfilled prophecy.',
        assessment: 'Campaign attested · fulfillment disputed',
        sourceIds: ['bm33041', 'ouysook2021', 'kahn2022'],
      },
      {
        id: 'egypt-forty-years',
        title: 'Forty years of desolation, followed by return',
        passages: [ref('Ezekiel 29:10–16', 'Ezekiel', 29, 10)],
        oracleDate: 'The oracle opens in exile year 10, month 10, day 12 (Ezekiel 29:1).',
        eventDate: null,
        event: 'No securely identified forty-year period is assigned here for the stated desolation, scattering and return.',
        placement: 'The reviewed sources do not locate a corresponding forty-year interval within Ezekiel, Kings or Ezra. It would be misleading to draw one on the historical timeline.',
        contextPassages: [ref('Ezekiel 29:1', 'Ezekiel', 29), ref('Ezekiel 29:11–14', 'Ezekiel', 29, 11)],
        connection: 'The duration and return are distinct claims in the passage; evidence of one campaign cannot establish them automatically.',
        evidence: 'Herodotus describes prosperity under Amasis in Histories 2.177 and a long reign in 3.10. This is a later literary account, not a contemporary census, but it is a reason to question an assumed nationwide forty-year abandonment.',
        limits: 'A symbolic reading, a limited historical application or a future fulfillment would require its own interpretive argument. This table does not choose between those readings or turn missing confirmation into a date.',
        assessment: 'No secure historical match',
        sourceIds: ['herodotus2177', 'herodotus310'],
      },
      {
        id: 'egypt-persian-conquest',
        title: 'Later Persian rule as a comparison',
        passages: [ref('Ezekiel 29:13–16', 'Ezekiel', 29, 13)],
        oracleDate: 'Part of the oracle introduced in Ezekiel 29:1; separate from its later year-27 addition.',
        eventDate: '525 BC · Persian conquest under Cambyses',
        event: 'Egypt comes under Persian rule. Herodotus narrates the capture of its king after Memphis surrenders; Egyptian independence later returns in 404 BC.',
        placement: 'After the Cyrus-era return in Ezra 1 and before the Darius-era completion of the temple in Ezra 6. Those chapters supply wider context; neither narrates this Egyptian conquest.',
        contextPassages: [ref('Ezra 1:1–4', 'Ezra', 1), ref('Ezra 6:14–15', 'Ezra', 6, 14)],
        connection: 'Loss of independence can be compared with the reduced political standing pictured in Ezekiel 29:14–16.',
        evidence: 'Herodotus supplies an ancient narrative; the Metropolitan Museum supplies the conventional dates for Persian rule and the renewed native dynasties.',
        limits: 'Cambyses is not Nebuchadnezzar. This later conquest cannot simply be substituted for the named king in Ezekiel 29:19, and neither a forty-year desolation nor a permanent end to native rule follows from it.',
        assessment: 'Later comparison · not a direct match',
        sourceIds: ['herodotus314', 'metLatePeriod'],
      },
    ],
    sources: [
      {
        id: 'bm33041',
        title: 'British Museum · tablet BM 33041 (1878,1015.22)',
        kind: 'Primary artifact · museum catalogue',
        url: 'https://www.britishmuseum.org/collection/object/W_1878-1015-22',
        note: 'Catalogue identifies a campaign in Nebuchadnezzar’s 37th year. The fragment does not provide a complete history of its outcome.',
      },
      {
        id: 'ouysook2021',
        title: 'Peerapat Ouysook (2021), Royal Inscriptions, p. 182, note 105',
        kind: 'Modern scholarly assessment',
        url: 'https://api.repository.cam.ac.uk/server/api/core/bitstreams/77b2c5db-900a-4f70-b297-cf8eafac8c1e/content#page=193',
        note: 'Cambridge dissertation; stresses the broken tablet’s limited evidence and the disputed extent of Babylonian success.',
      },
      {
        id: 'kahn2022',
        title: 'Dan’el Kahn (2022) · Nebuchadnezzar and Egypt',
        kind: 'Modern scholarly interpretation',
        url: 'https://www.thetorah.com/article/nebuchadnezzar-fails-to-conquer-egypt-so-jeremiahs-prophecy-was-updated',
        note: 'Sections on the Egyptian civil war and brief Babylonian success explain the proposed 568/567 BC connection. His separate theory of prophetic editing is not adopted as a fact by this table.',
      },
      {
        id: 'herodotus2177',
        title: 'Herodotus · Histories 2.177',
        kind: 'Ancient literary account · later than the events',
        url: 'https://lexundria.com/hdt/2.177.1/mcly',
        note: 'Reports prosperity under Amasis. Treat its numerical and rhetorical claims critically.',
      },
      {
        id: 'herodotus310',
        title: 'Herodotus · Histories 3.10',
        kind: 'Ancient literary account · later than the events',
        url: 'https://lexundria.com/hdt/3.10.1/mcly',
        note: 'Describes Amasis’s long reign and death before Cambyses’s arrival.',
      },
      {
        id: 'herodotus314',
        title: 'Herodotus · Histories 3.14',
        kind: 'Ancient literary account · later than the events',
        url: 'https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0126%3Abook%3D3%3Achapter%3D14',
        note: 'Places the captured Egyptian king in Cambyses’s hands after Memphis surrenders.',
      },
      {
        id: 'metLatePeriod',
        title: 'Metropolitan Museum · Egypt in the Late Period',
        kind: 'Modern curatorial history',
        url: 'https://www.metmuseum.org/essays/egypt-in-the-late-period-ca-712-332-b-c',
        note: 'Dates the first Persian period to 525–404 BC and describes the return of native dynasties.',
      },
    ],
  },
}
