import sharp from 'sharp'
import {chromium,firefox,expect} from '@playwright/test'
import core from '../../packages/service-core/index.js'
import assert from 'node:assert/strict'
import {writeFile,mkdir} from 'node:fs/promises'
import {resolve} from 'node:path'
const evidence=resolve(process.env.CANVAS_TEST_EVIDENCE || 'test-results/canvas-editor')
await mkdir(evidence,{recursive:true})
const pixel=await sharp({create:{width:1,height:1,channels:3,background:'#3050d0'}}).png().toBuffer()
const results=[]
for(const [name,engine] of Object.entries({chromium,firefox})) {
 const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[]
 page.setDefaultTimeout(10000)
 page.on('pageerror',e=>{errors.push(e.message);console.log('BROWSER ERROR',name,e.message)})
 console.log('Start',name)
 let project=core.createServiceProject({id:'canvas-rehearsal',title:'Canvas rehearsal',serviceDate:'2026-09-16',preferredProfileId:'main-sanctuary',presetPack:{id:'main-sanctuary',version:1,sha256:null},channels:[{id:'english',label:'English',language:'en'},{id:'russian',label:'Russian',language:'ru'},{id:'media',label:'Stage',language:'ru'}]})
 project=core.addProjectItem(project,{id:'initial',kind:'sermon',title:'Starting slide',presetId:'wotbc-sermon',textByChannel:{english:'Starting slide',russian:'Начало'}})
 let saved={syncId:'canvas-rehearsal',syncVersion:1,revision:1,status:'planning',project},lastSave
 await page.route('**/api/community/**',async route=>{
  const url=new URL(route.request().url()),method=route.request().method()
  if(url.pathname.endsWith('/library/songs') || url.pathname.endsWith('/sermon-presentations'))return route.fulfill({json:{items:[]}})
  if(url.pathname.endsWith('/library/bible-passage'))return route.fulfill({json:{books:[]}})
  if(url.pathname.includes('/assets/') && method==='GET')return route.fulfill({body:pixel,contentType:'image/png'})
  if(url.pathname.includes('/assets/') && method==='PUT')return route.fulfill({json:{asset:{mediaType:'image/png',size:pixel.length,width:1,height:1,orientation:1}}})
  if(method==='PUT'){
   lastSave=route.request().postDataJSON();const doc=core.parseHeritageServiceDocumentSource(lastSave.documentSource)
   saved={...saved,syncVersion:saved.syncVersion+1,revision:doc.project.revision,project:doc.project};return route.fulfill({json:{serviceDocument:saved}})
  }
  if(url.pathname==='/api/community/service-documents')return route.fulfill({json:{items:[]}})
  if(url.pathname.endsWith('/canvas-rehearsal'))return route.fulfill({json:{serviceDocument:saved}})
  return route.fulfill({json:{items:[]}})
 })
 await page.goto('http://127.0.0.1:4199/community-server/tests/browser/planner.html')
 await page.screenshot({path:`${evidence}/initial-${name}.png`})
 console.log('Planner loaded', name)
 await page.getByRole('button',{name:/Other Move text/}).click()
 console.log('Other created')
 await page.getByRole('button',{name:'Add text',exact:true}).click()
 const text=page.getByRole('textbox',{name:'Text object 1',exact:true})
 await text.fill('Love is patient · Любовь долготерпит')
 await text.press('Tab')
 await text.evaluate(element=>{const range=document.createRange();range.setStart(element.firstChild,0);range.setEnd(element.firstChild,4);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'))})
 await page.getByRole('button',{name:'Bold',exact:true}).click()
 await page.getByLabel('Text highlight',{exact:true}).fill('#8a5a00')
 await expect(text.locator('span').first()).toHaveCSS('background-color','rgb(138, 90, 0)')
 console.log('Text highlighted')
 await page.getByRole('button',{name:'Add brace }',exact:true}).click()
 await page.getByLabel('Rotation °',{exact:true}).fill('45')
 await page.getByLabel('Width %',{exact:true}).fill('14')
 const handle=page.getByRole('button',{name:'Move selected object',exact:true}),before=await handle.boundingBox()
 await page.mouse.move(before.x+12,before.y+12);await page.mouse.down();await page.mouse.move(before.x+70,before.y+42,{steps:8});await page.mouse.up()
 await page.getByRole('button',{name:'Outline circle',exact:true}).click()
 await page.getByLabel('Left %',{exact:true}).fill('60')
 const resize=await page.getByRole('button',{name:'Resize selected object',exact:true}).boundingBox();await page.mouse.move(resize.x+12,resize.y+12);await page.mouse.down();await page.mouse.move(resize.x+44,resize.y+30,{steps:5});await page.mouse.up()
 await page.getByRole('button',{name:'Filled circle',exact:true}).click()
 await page.getByLabel('Left %',{exact:true}).fill('70')
 const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add image',exact:true}).click()
 await (await chooser).setFiles({name:'pixel.png',mimeType:'image/png',buffer:pixel})
 await expect(page.locator('.heritage-canvas__object')).toHaveCount(5)
 await page.getByRole('button',{name:'Save sermon slides',exact:true}).click()
 await expect(page.getByText('2 slides · Saved v2',{exact:true})).toBeVisible()
 let other=Object.values(saved.project.items).find(item=>item.sermonTemplate==='other')
 assert.equal(other.objectsByChannel.english.length,5)
 assert.equal(other.objectsByChannel.english[0].spans[0].background,'#8a5a00')
 assert.equal(other.objectsByChannel.english[0].spans[0].weight,'700')
 assert.equal(other.objectsByChannel.english[1].frame.rotation,45)
 assert(other.objectsByChannel.english[1].frame.x>.15)
 assert(Object.keys(saved.project.assets).length===1)
 await page.screenshot({path:`${evidence}/${name}.png`,fullPage:true})
 await page.reload()
 await page.getByText('Other slide',{exact:true}).first().click()
 await expect(page.locator('.heritage-canvas__object')).toHaveCount(5)
 await expect(page.locator('.heritage-canvas img')).toHaveJSProperty('naturalWidth',1)
 await page.getByRole('tab',{name:'Russian',exact:true}).click()
 await page.getByRole('button',{name:'Add text',exact:true}).click()
 await page.getByRole('textbox',{name:'Text object 1',exact:true}).fill('Любовь никогда не перестает')
 await page.getByRole('textbox',{name:'Text object 1',exact:true}).press('Tab')
 await page.getByRole('tab',{name:'Stage-Facing Screen',exact:true}).click()
 await expect(page.getByText('Любовь никогда не перестает',{exact:true})).toBeVisible()
 assert.deepEqual(errors,[])
 results.push({browser:name,saveReopen:true,dragResizeRotation:true,highlight:true,image:true,russianStage:true,errors})
 await browser.close()
}
await writeFile(`${evidence}/results.json`,JSON.stringify(results,null,2)+'\n')
console.log(JSON.stringify(results,null,2))
